// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        output_conv3,
        output_conv3_ap_vld,
        padding
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_pp0_stage0 = 9'd16;
parameter    ap_ST_fsm_state7 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_pp1_stage0 = 9'd128;
parameter    ap_ST_fsm_state56 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] p_read;
output  [63:0] output_conv3;
output   output_conv3_ap_vld;
input  [30:0] padding;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_conv3_ap_vld;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] bias_conv3_address0;
reg    bias_conv3_ce0;
wire   [63:0] bias_conv3_q0;
reg   [2:0] line_buffer_1_5_address0;
reg    line_buffer_1_5_ce0;
wire   [63:0] line_buffer_1_5_q0;
reg   [2:0] line_buffer_1_5_address1;
reg    line_buffer_1_5_ce1;
reg    line_buffer_1_5_we1;
wire   [63:0] line_buffer_1_5_q1;
reg   [2:0] line_buffer_0_5_address0;
reg    line_buffer_0_5_ce0;
reg    line_buffer_0_5_we0;
wire   [63:0] line_buffer_0_5_q0;
reg   [2:0] line_buffer_0_5_address1;
reg    line_buffer_0_5_ce1;
wire   [63:0] line_buffer_0_5_q1;
reg   [2:0] line_buffer_2_5_address0;
reg    line_buffer_2_5_ce0;
reg    line_buffer_2_5_we0;
wire   [63:0] line_buffer_2_5_d0;
wire   [63:0] line_buffer_2_5_q0;
reg   [2:0] line_buffer_2_5_address1;
reg    line_buffer_2_5_ce1;
wire   [63:0] line_buffer_2_5_q1;
wire   [9:0] kernel_conv3_address0;
reg    kernel_conv3_ce0;
wire   [63:0] kernel_conv3_q0;
wire   [9:0] kernel_conv3_address1;
reg    kernel_conv3_ce1;
wire   [63:0] kernel_conv3_q1;
wire   [9:0] kernel_conv3_address2;
reg    kernel_conv3_ce2;
wire   [63:0] kernel_conv3_q2;
wire   [9:0] kernel_conv3_address3;
reg    kernel_conv3_ce3;
wire   [63:0] kernel_conv3_q3;
wire   [9:0] kernel_conv3_address4;
reg    kernel_conv3_ce4;
wire   [63:0] kernel_conv3_q4;
wire   [9:0] kernel_conv3_address5;
reg    kernel_conv3_ce5;
wire   [63:0] kernel_conv3_q5;
wire   [9:0] kernel_conv3_address6;
reg    kernel_conv3_ce6;
wire   [63:0] kernel_conv3_q6;
wire   [9:0] kernel_conv3_address7;
reg    kernel_conv3_ce7;
wire   [63:0] kernel_conv3_q7;
wire   [9:0] kernel_conv3_address8;
reg    kernel_conv3_ce8;
wire   [63:0] kernel_conv3_q8;
reg   [2:0] j_reg_432;
reg   [30:0] b_reg_443;
reg   [63:0] window_buffer_load_3_0_reg_454;
wire    ap_block_state9_pp1_stage0_iter0;
wire    ap_block_state10_pp1_stage0_iter1;
wire    ap_block_state11_pp1_stage0_iter2;
wire    ap_block_state12_pp1_stage0_iter3;
wire    ap_block_state13_pp1_stage0_iter4;
wire    ap_block_state14_pp1_stage0_iter5;
wire    ap_block_state15_pp1_stage0_iter6;
wire    ap_block_state16_pp1_stage0_iter7;
wire    ap_block_state17_pp1_stage0_iter8;
wire    ap_block_state18_pp1_stage0_iter9;
wire    ap_block_state19_pp1_stage0_iter10;
wire    ap_block_state20_pp1_stage0_iter11;
wire    ap_block_state21_pp1_stage0_iter12;
wire    ap_block_state22_pp1_stage0_iter13;
wire    ap_block_state23_pp1_stage0_iter14;
wire    ap_block_state24_pp1_stage0_iter15;
wire    ap_block_state25_pp1_stage0_iter16;
wire    ap_block_state26_pp1_stage0_iter17;
wire    ap_block_state27_pp1_stage0_iter18;
wire    ap_block_state28_pp1_stage0_iter19;
wire    ap_block_state29_pp1_stage0_iter20;
wire    ap_block_state30_pp1_stage0_iter21;
wire    ap_block_state31_pp1_stage0_iter22;
wire    ap_block_state32_pp1_stage0_iter23;
wire    ap_block_state33_pp1_stage0_iter24;
wire    ap_block_state34_pp1_stage0_iter25;
wire    ap_block_state35_pp1_stage0_iter26;
wire    ap_block_state36_pp1_stage0_iter27;
wire    ap_block_state37_pp1_stage0_iter28;
wire    ap_block_state38_pp1_stage0_iter29;
wire    ap_block_state39_pp1_stage0_iter30;
wire    ap_block_state40_pp1_stage0_iter31;
wire    ap_block_state41_pp1_stage0_iter32;
wire    ap_block_state42_pp1_stage0_iter33;
wire    ap_block_state43_pp1_stage0_iter34;
wire    ap_block_state44_pp1_stage0_iter35;
wire    ap_block_state45_pp1_stage0_iter36;
wire    ap_block_state46_pp1_stage0_iter37;
wire    ap_block_state47_pp1_stage0_iter38;
wire    ap_block_state48_pp1_stage0_iter39;
wire    ap_block_state49_pp1_stage0_iter40;
wire    ap_block_state50_pp1_stage0_iter41;
wire    ap_block_state51_pp1_stage0_iter42;
wire    ap_block_state52_pp1_stage0_iter43;
wire    ap_block_state53_pp1_stage0_iter44;
wire    ap_block_state54_pp1_stage0_iter45;
wire    ap_block_state55_pp1_stage0_iter46;
wire    ap_block_pp1_stage0_11001;
reg   [63:0] window_buffer_load_0_reg_464;
reg   [63:0] window_buffer_load_3_1_reg_475;
reg   [63:0] window_buffer_load_1_reg_485;
reg   [63:0] window_buffer_load_3_2_reg_496;
reg   [63:0] window_buffer_load_2_reg_506;
wire   [31:0] add_ln31_fu_613_p2;
reg   [31:0] add_ln31_reg_1155;
wire   [0:0] icmp_ln42_fu_619_p2;
reg   [0:0] icmp_ln42_reg_1160;
wire   [31:0] sub13_fu_625_p2;
reg   [31:0] sub13_reg_1164;
wire   [31:0] sub47_fu_631_p2;
reg   [31:0] sub47_reg_1169;
wire   [0:0] cmp4827_fu_637_p2;
reg   [0:0] cmp4827_reg_1174;
wire   [63:0] bitcast_ln49_fu_643_p1;
reg   [63:0] bitcast_ln49_reg_1178;
wire   [2:0] empty_23_fu_652_p1;
reg   [2:0] empty_23_reg_1183;
wire    ap_CS_fsm_state2;
reg   [63:0] bias_conv3_load_reg_1194;
wire    ap_CS_fsm_state3;
wire   [9:0] add_ln39_fu_706_p2;
reg   [9:0] add_ln39_reg_1202;
wire   [0:0] icmp_ln40_fu_712_p2;
reg   [0:0] icmp_ln40_reg_1207;
wire   [0:0] icmp_ln39_fu_700_p2;
wire   [0:0] and_ln39_fu_790_p2;
reg   [0:0] and_ln39_reg_1214;
wire   [3:0] select_ln39_8_fu_796_p3;
reg   [3:0] select_ln39_8_reg_1220;
wire   [3:0] select_ln40_7_fu_940_p3;
reg   [3:0] select_ln40_7_reg_1275;
wire   [3:0] select_ln40_fu_958_p3;
reg   [3:0] select_ln40_reg_1280;
wire    ap_CS_fsm_state4;
wire   [63:0] select_ln40_5_fu_966_p3;
reg   [63:0] select_ln40_5_reg_1286;
reg   [63:0] kernel_conv3_load_reg_1291;
reg   [63:0] kernel_conv3_load_1_reg_1296;
reg   [63:0] kernel_conv3_load_2_reg_1301;
reg   [63:0] kernel_conv3_load_3_reg_1306;
reg   [63:0] kernel_conv3_load_4_reg_1311;
reg   [63:0] kernel_conv3_load_5_reg_1316;
reg   [63:0] kernel_conv3_load_6_reg_1321;
reg   [63:0] kernel_conv3_load_7_reg_1326;
reg   [63:0] kernel_conv3_load_8_reg_1331;
wire   [0:0] or_ln45_fu_985_p2;
reg   [0:0] or_ln45_reg_1336;
wire   [0:0] icmp_ln42_2_fu_995_p2;
reg   [0:0] icmp_ln42_2_reg_1341;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] add_ln42_fu_1000_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] j_cast4_fu_1006_p1;
reg   [63:0] j_cast4_reg_1350;
reg   [2:0] line_buffer_1_5_addr_reg_1355;
wire   [0:0] icmp_ln52_fu_1051_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln64_fu_1061_p2;
reg   [0:0] icmp_ln64_reg_1400;
wire    ap_CS_fsm_pp1_stage0;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter1_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter2_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter3_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter4_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter5_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter6_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter7_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter8_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter9_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter10_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter11_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter12_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter13_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter14_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter15_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter16_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter17_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter18_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter19_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter20_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter21_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter22_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter23_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter24_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter25_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter26_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter27_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter28_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter29_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter30_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter31_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter32_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter33_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter34_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter35_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter36_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter37_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter38_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter39_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter40_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter41_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter42_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter43_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter44_reg;
reg   [0:0] icmp_ln64_reg_1400_pp1_iter45_reg;
wire   [30:0] add_ln64_fu_1066_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [63:0] p_cast_fu_1082_p1;
reg   [63:0] p_cast_reg_1409;
reg   [63:0] p_cast_reg_1409_pp1_iter1_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter2_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter3_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter4_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter5_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter6_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter7_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter8_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter9_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter10_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter11_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter12_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter13_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter14_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter15_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter16_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter17_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter18_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter19_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter20_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter21_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter22_reg;
reg   [63:0] p_cast_reg_1409_pp1_iter23_reg;
reg   [63:0] line_buffer_0_5_load_2_reg_1420;
reg    ap_enable_reg_pp1_iter1;
reg   [63:0] line_buffer_0_5_load_2_reg_1420_pp1_iter2_reg;
wire   [63:0] grp_fu_558_p2;
reg   [63:0] mul_reg_1426;
wire   [63:0] grp_fu_563_p2;
reg   [63:0] mul_0_1_reg_1431;
reg   [63:0] mul_0_1_reg_1431_pp1_iter6_reg;
reg   [63:0] mul_0_1_reg_1431_pp1_iter7_reg;
reg   [63:0] mul_0_1_reg_1431_pp1_iter8_reg;
wire   [63:0] grp_fu_568_p2;
reg   [63:0] mul_0_2_reg_1436;
reg   [63:0] mul_0_2_reg_1436_pp1_iter7_reg;
reg   [63:0] mul_0_2_reg_1436_pp1_iter8_reg;
reg   [63:0] mul_0_2_reg_1436_pp1_iter9_reg;
reg   [63:0] mul_0_2_reg_1436_pp1_iter10_reg;
reg   [63:0] mul_0_2_reg_1436_pp1_iter11_reg;
reg   [63:0] mul_0_2_reg_1436_pp1_iter12_reg;
wire   [63:0] grp_fu_517_p2;
reg   [63:0] sum_4_reg_1441;
wire   [63:0] grp_fu_522_p2;
reg   [63:0] sum_4_0_1_reg_1451;
reg   [63:0] line_buffer_1_5_load_3_reg_1456;
reg    ap_enable_reg_pp1_iter13;
reg   [63:0] line_buffer_1_5_load_3_reg_1456_pp1_iter14_reg;
wire   [63:0] grp_fu_526_p2;
reg   [63:0] sum_4_0_2_reg_1462;
wire   [63:0] grp_fu_572_p2;
reg   [63:0] mul_1_reg_1467;
wire   [63:0] grp_fu_577_p2;
reg   [63:0] mul_1_1_reg_1472;
reg   [63:0] mul_1_1_reg_1472_pp1_iter18_reg;
reg   [63:0] mul_1_1_reg_1472_pp1_iter19_reg;
reg   [63:0] mul_1_1_reg_1472_pp1_iter20_reg;
wire   [63:0] grp_fu_582_p2;
reg   [63:0] mul_1_2_reg_1477;
reg   [63:0] mul_1_2_reg_1477_pp1_iter19_reg;
reg   [63:0] mul_1_2_reg_1477_pp1_iter20_reg;
reg   [63:0] mul_1_2_reg_1477_pp1_iter21_reg;
reg   [63:0] mul_1_2_reg_1477_pp1_iter22_reg;
reg   [63:0] mul_1_2_reg_1477_pp1_iter23_reg;
reg   [63:0] mul_1_2_reg_1477_pp1_iter24_reg;
wire   [63:0] grp_fu_530_p2;
reg   [63:0] sum_4_1_reg_1482;
wire   [63:0] grp_fu_534_p2;
reg   [63:0] sum_4_1_1_reg_1492;
reg   [63:0] line_buffer_2_5_load_3_reg_1497;
reg    ap_enable_reg_pp1_iter25;
reg   [63:0] line_buffer_2_5_load_3_reg_1497_pp1_iter26_reg;
wire   [63:0] grp_fu_538_p2;
reg   [63:0] sum_4_1_2_reg_1503;
wire   [63:0] grp_fu_586_p2;
reg   [63:0] mul_2_reg_1508;
wire   [63:0] grp_fu_591_p2;
reg   [63:0] mul_2_1_reg_1513;
reg   [63:0] mul_2_1_reg_1513_pp1_iter30_reg;
reg   [63:0] mul_2_1_reg_1513_pp1_iter31_reg;
reg   [63:0] mul_2_1_reg_1513_pp1_iter32_reg;
wire   [63:0] grp_fu_596_p2;
reg   [63:0] mul_2_2_reg_1518;
reg   [63:0] mul_2_2_reg_1518_pp1_iter31_reg;
reg   [63:0] mul_2_2_reg_1518_pp1_iter32_reg;
reg   [63:0] mul_2_2_reg_1518_pp1_iter33_reg;
reg   [63:0] mul_2_2_reg_1518_pp1_iter34_reg;
reg   [63:0] mul_2_2_reg_1518_pp1_iter35_reg;
reg   [63:0] mul_2_2_reg_1518_pp1_iter36_reg;
wire   [63:0] grp_fu_542_p2;
reg   [63:0] sum_4_2_reg_1523;
wire   [63:0] grp_fu_546_p2;
reg   [63:0] sum_4_2_1_reg_1528;
wire   [63:0] grp_fu_550_p2;
reg   [63:0] sum_4_2_2_reg_1533;
wire   [63:0] grp_fu_554_p2;
reg   [63:0] sum_reg_1538;
reg   [63:0] sum_reg_1538_pp1_iter45_reg;
wire   [3:0] add_ln41_fu_1137_p2;
wire    ap_CS_fsm_state56;
wire   [7:0] select_ln40_8_fu_1148_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
reg    ap_enable_reg_pp1_iter11;
reg    ap_enable_reg_pp1_iter12;
reg    ap_enable_reg_pp1_iter14;
reg    ap_enable_reg_pp1_iter15;
reg    ap_enable_reg_pp1_iter16;
reg    ap_enable_reg_pp1_iter17;
reg    ap_enable_reg_pp1_iter18;
reg    ap_enable_reg_pp1_iter19;
reg    ap_enable_reg_pp1_iter20;
reg    ap_enable_reg_pp1_iter21;
reg    ap_enable_reg_pp1_iter22;
reg    ap_enable_reg_pp1_iter23;
reg    ap_enable_reg_pp1_iter24;
reg    ap_enable_reg_pp1_iter26;
reg    ap_condition_pp1_exit_iter25_state34;
reg    ap_enable_reg_pp1_iter27;
reg    ap_enable_reg_pp1_iter28;
reg    ap_enable_reg_pp1_iter29;
reg    ap_enable_reg_pp1_iter30;
reg    ap_enable_reg_pp1_iter31;
reg    ap_enable_reg_pp1_iter32;
reg    ap_enable_reg_pp1_iter33;
reg    ap_enable_reg_pp1_iter34;
reg    ap_enable_reg_pp1_iter35;
reg    ap_enable_reg_pp1_iter36;
reg    ap_enable_reg_pp1_iter37;
reg    ap_enable_reg_pp1_iter38;
reg    ap_enable_reg_pp1_iter39;
reg    ap_enable_reg_pp1_iter40;
reg    ap_enable_reg_pp1_iter41;
reg    ap_enable_reg_pp1_iter42;
reg    ap_enable_reg_pp1_iter43;
reg    ap_enable_reg_pp1_iter44;
reg    ap_enable_reg_pp1_iter45;
reg    ap_enable_reg_pp1_iter46;
reg   [3:0] num_ker_reg_374;
reg   [9:0] indvar_flatten109_reg_386;
reg   [3:0] num_channel_reg_397;
reg   [7:0] indvar_flatten_reg_408;
reg   [3:0] i_reg_420;
wire    ap_block_pp1_stage0;
reg   [63:0] ap_phi_mux_window_buffer_load_0_phi_fu_467_p4;
reg   [63:0] ap_phi_mux_window_buffer_load_1_phi_fu_488_p4;
reg   [63:0] ap_phi_mux_window_buffer_load_2_phi_fu_509_p4;
wire   [63:0] zext_ln40_fu_647_p1;
wire   [63:0] zext_ln40_10_fu_810_p1;
wire   [63:0] zext_ln83_8_fu_847_p1;
wire   [63:0] zext_ln40_11_fu_858_p1;
wire   [63:0] zext_ln40_12_fu_869_p1;
wire   [63:0] zext_ln40_13_fu_880_p1;
wire   [63:0] zext_ln40_14_fu_891_p1;
wire   [63:0] zext_ln40_15_fu_902_p1;
wire   [63:0] zext_ln40_16_fu_913_p1;
wire   [63:0] zext_ln40_17_fu_924_p1;
wire   [63:0] zext_ln40_18_fu_935_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp1_stage0_01001;
wire   [31:0] shl_ln_fu_605_p3;
wire   [2:0] empty_fu_660_p1;
wire   [5:0] add_ln83_4_fu_672_p0;
wire   [5:0] add_ln83_4_fu_672_p1;
wire   [5:0] add_ln83_4_fu_672_p2;
wire   [8:0] tmp_fu_682_p4;
wire   [9:0] add_ln83_fu_694_p0;
wire   [9:0] add_ln83_fu_694_p1;
wire   [3:0] add_ln39_2_fu_726_p2;
wire   [2:0] empty_29_fu_736_p1;
wire   [5:0] add_ln83_5_fu_748_p0;
wire   [5:0] add_ln83_5_fu_748_p1;
wire   [5:0] add_ln83_5_fu_748_p2;
wire   [5:0] select_ln39_5_fu_758_p3;
wire   [9:0] zext_ln83_6_fu_754_p1;
wire   [9:0] add_ln83_fu_694_p2;
wire   [0:0] icmp_ln41_fu_784_p2;
wire   [0:0] xor_ln39_fu_778_p2;
wire   [3:0] select_ln39_fu_718_p3;
wire   [3:0] add_ln40_fu_804_p2;
wire   [2:0] empty_30_fu_815_p1;
wire   [8:0] tmp_mid1_fu_819_p4;
wire   [9:0] add_ln83_6_fu_833_p0;
wire   [9:0] add_ln83_6_fu_833_p1;
wire   [9:0] add_ln83_6_fu_833_p2;
wire   [9:0] select_ln39_7_fu_770_p3;
wire   [9:0] select_ln40_6_fu_839_p3;
wire   [9:0] add_ln40_10_fu_852_p2;
wire   [9:0] add_ln40_11_fu_863_p2;
wire   [9:0] add_ln40_12_fu_874_p2;
wire   [9:0] add_ln40_13_fu_885_p2;
wire   [9:0] add_ln40_14_fu_896_p2;
wire   [9:0] add_ln40_15_fu_907_p2;
wire   [9:0] add_ln40_16_fu_918_p2;
wire   [9:0] add_ln40_17_fu_929_p2;
wire   [0:0] or_ln40_fu_954_p2;
wire   [63:0] select_ln39_6_fu_948_p3;
wire   [0:0] icmp_ln45_4_fu_973_p2;
wire   [0:0] icmp_ln45_5_fu_979_p2;
wire   [31:0] j_cast_fu_991_p1;
wire   [0:0] icmp_ln45_2_fu_1018_p2;
wire   [0:0] icmp_ln45_fu_1012_p2;
wire   [0:0] or_ln45_3_fu_1023_p2;
wire   [0:0] or_ln45_4_fu_1029_p2;
wire   [2:0] tmp_2_fu_1042_p4;
wire   [31:0] b_cast_fu_1057_p1;
wire   [2:0] empty_27_fu_1076_p1;
wire   [2:0] empty_27_fu_1076_p2;
wire   [63:0] bitcast_ln11_fu_1087_p1;
wire   [10:0] tmp_5_fu_1090_p4;
wire   [51:0] trunc_ln11_fu_1100_p1;
wire   [0:0] icmp_ln11_2_fu_1110_p2;
wire   [0:0] icmp_ln11_fu_1104_p2;
wire   [0:0] or_ln11_fu_1116_p2;
wire   [0:0] grp_fu_600_p2;
wire   [0:0] and_ln11_fu_1122_p2;
wire   [7:0] add_ln40_18_fu_1142_p2;
wire    ap_block_pp1_stage0_00001;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter13 = 1'b0;
#0 ap_enable_reg_pp1_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter12 = 1'b0;
#0 ap_enable_reg_pp1_iter14 = 1'b0;
#0 ap_enable_reg_pp1_iter15 = 1'b0;
#0 ap_enable_reg_pp1_iter16 = 1'b0;
#0 ap_enable_reg_pp1_iter17 = 1'b0;
#0 ap_enable_reg_pp1_iter18 = 1'b0;
#0 ap_enable_reg_pp1_iter19 = 1'b0;
#0 ap_enable_reg_pp1_iter20 = 1'b0;
#0 ap_enable_reg_pp1_iter21 = 1'b0;
#0 ap_enable_reg_pp1_iter22 = 1'b0;
#0 ap_enable_reg_pp1_iter23 = 1'b0;
#0 ap_enable_reg_pp1_iter24 = 1'b0;
#0 ap_enable_reg_pp1_iter26 = 1'b0;
#0 ap_enable_reg_pp1_iter27 = 1'b0;
#0 ap_enable_reg_pp1_iter28 = 1'b0;
#0 ap_enable_reg_pp1_iter29 = 1'b0;
#0 ap_enable_reg_pp1_iter30 = 1'b0;
#0 ap_enable_reg_pp1_iter31 = 1'b0;
#0 ap_enable_reg_pp1_iter32 = 1'b0;
#0 ap_enable_reg_pp1_iter33 = 1'b0;
#0 ap_enable_reg_pp1_iter34 = 1'b0;
#0 ap_enable_reg_pp1_iter35 = 1'b0;
#0 ap_enable_reg_pp1_iter36 = 1'b0;
#0 ap_enable_reg_pp1_iter37 = 1'b0;
#0 ap_enable_reg_pp1_iter38 = 1'b0;
#0 ap_enable_reg_pp1_iter39 = 1'b0;
#0 ap_enable_reg_pp1_iter40 = 1'b0;
#0 ap_enable_reg_pp1_iter41 = 1'b0;
#0 ap_enable_reg_pp1_iter42 = 1'b0;
#0 ap_enable_reg_pp1_iter43 = 1'b0;
#0 ap_enable_reg_pp1_iter44 = 1'b0;
#0 ap_enable_reg_pp1_iter45 = 1'b0;
#0 ap_enable_reg_pp1_iter46 = 1'b0;
end

CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s_bias_conv3 #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
bias_conv3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_conv3_address0),
    .ce0(bias_conv3_ce0),
    .q0(bias_conv3_q0)
);

CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s_line_buffer_1_5 #(
    .DataWidth( 64 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
line_buffer_1_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_5_address0),
    .ce0(line_buffer_1_5_ce0),
    .q0(line_buffer_1_5_q0),
    .address1(line_buffer_1_5_address1),
    .ce1(line_buffer_1_5_ce1),
    .we1(line_buffer_1_5_we1),
    .d1(line_buffer_2_5_q0),
    .q1(line_buffer_1_5_q1)
);

CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s_line_buffer_0_5 #(
    .DataWidth( 64 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
line_buffer_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_0_5_address0),
    .ce0(line_buffer_0_5_ce0),
    .we0(line_buffer_0_5_we0),
    .d0(line_buffer_1_5_q0),
    .q0(line_buffer_0_5_q0),
    .address1(line_buffer_0_5_address1),
    .ce1(line_buffer_0_5_ce1),
    .q1(line_buffer_0_5_q1)
);

CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s_line_buffer_0_5 #(
    .DataWidth( 64 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
line_buffer_2_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_2_5_address0),
    .ce0(line_buffer_2_5_ce0),
    .we0(line_buffer_2_5_we0),
    .d0(line_buffer_2_5_d0),
    .q0(line_buffer_2_5_q0),
    .address1(line_buffer_2_5_address1),
    .ce1(line_buffer_2_5_ce1),
    .q1(line_buffer_2_5_q1)
);

CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s_kernel_conv3 #(
    .DataWidth( 64 ),
    .AddressRange( 576 ),
    .AddressWidth( 10 ))
kernel_conv3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kernel_conv3_address0),
    .ce0(kernel_conv3_ce0),
    .q0(kernel_conv3_q0),
    .address1(kernel_conv3_address1),
    .ce1(kernel_conv3_ce1),
    .q1(kernel_conv3_q1),
    .address2(kernel_conv3_address2),
    .ce2(kernel_conv3_ce2),
    .q2(kernel_conv3_q2),
    .address3(kernel_conv3_address3),
    .ce3(kernel_conv3_ce3),
    .q3(kernel_conv3_q3),
    .address4(kernel_conv3_address4),
    .ce4(kernel_conv3_ce4),
    .q4(kernel_conv3_q4),
    .address5(kernel_conv3_address5),
    .ce5(kernel_conv3_ce5),
    .q5(kernel_conv3_q5),
    .address6(kernel_conv3_address6),
    .ce6(kernel_conv3_ce6),
    .q6(kernel_conv3_q6),
    .address7(kernel_conv3_address7),
    .ce7(kernel_conv3_ce7),
    .q7(kernel_conv3_q7),
    .address8(kernel_conv3_address8),
    .ce8(kernel_conv3_ce8),
    .q8(kernel_conv3_q8)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U108(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_1426),
    .din1(64'd0),
    .ce(1'b1),
    .dout(grp_fu_517_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U109(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_reg_1441),
    .din1(mul_0_1_reg_1431_pp1_iter8_reg),
    .ce(1'b1),
    .dout(grp_fu_522_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U110(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_0_1_reg_1451),
    .din1(mul_0_2_reg_1436_pp1_iter12_reg),
    .ce(1'b1),
    .dout(grp_fu_526_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U111(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_0_2_reg_1462),
    .din1(mul_1_reg_1467),
    .ce(1'b1),
    .dout(grp_fu_530_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U112(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_1_reg_1482),
    .din1(mul_1_1_reg_1472_pp1_iter20_reg),
    .ce(1'b1),
    .dout(grp_fu_534_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U113(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_1_1_reg_1492),
    .din1(mul_1_2_reg_1477_pp1_iter24_reg),
    .ce(1'b1),
    .dout(grp_fu_538_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U114(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_1_2_reg_1503),
    .din1(mul_2_reg_1508),
    .ce(1'b1),
    .dout(grp_fu_542_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U115(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_2_reg_1523),
    .din1(mul_2_1_reg_1513_pp1_iter32_reg),
    .ce(1'b1),
    .dout(grp_fu_546_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U116(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_2_1_reg_1528),
    .din1(mul_2_2_reg_1518_pp1_iter36_reg),
    .ce(1'b1),
    .dout(grp_fu_550_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U117(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_4_2_2_reg_1533),
    .din1(select_ln40_5_reg_1286),
    .ce(1'b1),
    .dout(grp_fu_554_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U118(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_0_phi_fu_467_p4),
    .din1(kernel_conv3_load_reg_1291),
    .ce(1'b1),
    .dout(grp_fu_558_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U119(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_3_0_reg_454),
    .din1(kernel_conv3_load_1_reg_1296),
    .ce(1'b1),
    .dout(grp_fu_563_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U120(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_0_5_load_2_reg_1420_pp1_iter2_reg),
    .din1(kernel_conv3_load_2_reg_1301),
    .ce(1'b1),
    .dout(grp_fu_568_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U121(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_1_phi_fu_488_p4),
    .din1(kernel_conv3_load_3_reg_1306),
    .ce(1'b1),
    .dout(grp_fu_572_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_3_1_reg_475),
    .din1(kernel_conv3_load_4_reg_1311),
    .ce(1'b1),
    .dout(grp_fu_577_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U123(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_1_5_load_3_reg_1456_pp1_iter14_reg),
    .din1(kernel_conv3_load_5_reg_1316),
    .ce(1'b1),
    .dout(grp_fu_582_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U124(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_2_phi_fu_509_p4),
    .din1(kernel_conv3_load_6_reg_1321),
    .ce(1'b1),
    .dout(grp_fu_586_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U125(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_3_2_reg_496),
    .din1(kernel_conv3_load_7_reg_1326),
    .ce(1'b1),
    .dout(grp_fu_591_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_2_5_load_3_reg_1497_pp1_iter26_reg),
    .din1(kernel_conv3_load_8_reg_1331),
    .ce(1'b1),
    .dout(grp_fu_596_p2)
);

CNN_CNN_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
CNN_dcmp_64ns_64ns_1_2_no_dsp_1_U127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_1538),
    .din1(64'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_600_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U128(
    .din0(shl_ln_fu_605_p3),
    .din1(32'd7),
    .dout(add_ln31_fu_613_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U129(
    .din0(shl_ln_fu_605_p3),
    .din1(32'd6),
    .dout(sub13_fu_625_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U130(
    .din0(shl_ln_fu_605_p3),
    .din1(32'd5),
    .dout(sub47_fu_631_p2)
);

CNN_CNN_add_6ns_6ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
CNN_add_6ns_6ns_6_1_1_U131(
    .din0(add_ln83_4_fu_672_p0),
    .din1(add_ln83_4_fu_672_p1),
    .dout(add_ln83_4_fu_672_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U132(
    .din0(add_ln83_fu_694_p0),
    .din1(add_ln83_fu_694_p1),
    .dout(add_ln83_fu_694_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U133(
    .din0(10'd1),
    .din1(indvar_flatten109_reg_386),
    .dout(add_ln39_fu_706_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U134(
    .din0(4'd1),
    .din1(num_channel_reg_397),
    .dout(add_ln39_2_fu_726_p2)
);

CNN_CNN_add_6ns_6ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
CNN_add_6ns_6ns_6_1_1_U135(
    .din0(add_ln83_5_fu_748_p0),
    .din1(add_ln83_5_fu_748_p1),
    .dout(add_ln83_5_fu_748_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U136(
    .din0(4'd1),
    .din1(select_ln39_fu_718_p3),
    .dout(add_ln40_fu_804_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U137(
    .din0(add_ln83_6_fu_833_p0),
    .din1(add_ln83_6_fu_833_p1),
    .dout(add_ln83_6_fu_833_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U138(
    .din0(10'd1),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_10_fu_852_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U139(
    .din0(10'd2),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_11_fu_863_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U140(
    .din0(10'd3),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_12_fu_874_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U141(
    .din0(10'd4),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_13_fu_885_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U142(
    .din0(10'd5),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_14_fu_896_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U143(
    .din0(10'd6),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_15_fu_907_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U144(
    .din0(10'd7),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_16_fu_918_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U145(
    .din0(10'd8),
    .din1(select_ln40_6_fu_839_p3),
    .dout(add_ln40_17_fu_929_p2)
);

CNN_CNN_add_3ns_3ns_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
CNN_add_3ns_3ns_3_1_1_U146(
    .din0(j_reg_432),
    .din1(3'd1),
    .dout(add_ln42_fu_1000_p2)
);

CNN_CNN_add_31ns_31ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
CNN_add_31ns_31ns_31_1_1_U147(
    .din0(b_reg_443),
    .din1(31'd1),
    .dout(add_ln64_fu_1066_p2)
);

CNN_CNN_add_3ns_3ns_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
CNN_add_3ns_3ns_3_1_1_U148(
    .din0(3'd2),
    .din1(empty_27_fu_1076_p1),
    .dout(empty_27_fu_1076_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U149(
    .din0(select_ln40_reg_1280),
    .din1(4'd1),
    .dout(add_ln41_fu_1137_p2)
);

CNN_CNN_add_8ns_8ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
CNN_add_8ns_8ns_8_1_1_U150(
    .din0(indvar_flatten_reg_408),
    .din1(8'd1),
    .dout(add_ln40_18_fu_1142_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln42_reg_1160 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln42_reg_1160 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter16 <= ap_enable_reg_pp1_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter17 <= ap_enable_reg_pp1_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter19 <= ap_enable_reg_pp1_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter20 <= ap_enable_reg_pp1_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter21 <= ap_enable_reg_pp1_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter22 <= ap_enable_reg_pp1_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter23 <= ap_enable_reg_pp1_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter24 <= ap_enable_reg_pp1_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter25 <= ap_enable_reg_pp1_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter25_state34)) begin
                ap_enable_reg_pp1_iter26 <= ap_enable_reg_pp1_iter24;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter26 <= ap_enable_reg_pp1_iter25;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter27 <= ap_enable_reg_pp1_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter28 <= ap_enable_reg_pp1_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter29 <= ap_enable_reg_pp1_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter30 <= ap_enable_reg_pp1_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter31 <= ap_enable_reg_pp1_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter32 <= ap_enable_reg_pp1_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter33 <= ap_enable_reg_pp1_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter34 <= ap_enable_reg_pp1_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter35 <= ap_enable_reg_pp1_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter36 <= ap_enable_reg_pp1_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter37 <= ap_enable_reg_pp1_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter38 <= ap_enable_reg_pp1_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter39 <= ap_enable_reg_pp1_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter40 <= ap_enable_reg_pp1_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter41 <= ap_enable_reg_pp1_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter42 <= ap_enable_reg_pp1_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter43 <= ap_enable_reg_pp1_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter44 <= ap_enable_reg_pp1_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter45 <= ap_enable_reg_pp1_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter46 <= ap_enable_reg_pp1_iter45;
        end else if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp1_iter46 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        b_reg_443 <= 31'd0;
    end else if (((icmp_ln64_fu_1061_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        b_reg_443 <= add_ln64_fu_1066_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        i_reg_420 <= add_ln41_fu_1137_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_420 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        indvar_flatten109_reg_386 <= add_ln39_reg_1202;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten109_reg_386 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        indvar_flatten_reg_408 <= select_ln40_8_fu_1148_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_408 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1160 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j_reg_432 <= 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_fu_995_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_432 <= add_ln42_fu_1000_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        num_channel_reg_397 <= select_ln39_8_reg_1220;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        num_channel_reg_397 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        num_ker_reg_374 <= select_ln40_7_reg_1275;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        num_ker_reg_374 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_0_reg_464 <= line_buffer_0_5_q0;
    end else if (((icmp_ln64_reg_1400_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_0_reg_464 <= window_buffer_load_3_0_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_1_reg_485 <= line_buffer_1_5_q0;
    end else if (((icmp_ln64_reg_1400_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_1_reg_485 <= window_buffer_load_3_1_reg_475;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_2_reg_506 <= line_buffer_2_5_q0;
    end else if (((icmp_ln64_reg_1400_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_2_reg_506 <= window_buffer_load_3_2_reg_496;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_3_0_reg_454 <= line_buffer_0_5_q1;
    end else if (((icmp_ln64_reg_1400_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_3_0_reg_454 <= line_buffer_0_5_load_2_reg_1420;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_3_1_reg_475 <= line_buffer_1_5_q1;
    end else if (((icmp_ln64_reg_1400_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_3_1_reg_475 <= line_buffer_1_5_load_3_reg_1456;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_3_2_reg_496 <= line_buffer_2_5_q1;
    end else if (((icmp_ln64_reg_1400_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_3_2_reg_496 <= line_buffer_2_5_load_3_reg_1497;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        add_ln31_reg_1155 <= add_ln31_fu_613_p2;
        bitcast_ln49_reg_1178 <= bitcast_ln49_fu_643_p1;
        cmp4827_reg_1174 <= cmp4827_fu_637_p2;
        icmp_ln42_reg_1160 <= icmp_ln42_fu_619_p2;
        sub13_reg_1164 <= sub13_fu_625_p2;
        sub47_reg_1169 <= sub47_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln39_reg_1202 <= add_ln39_fu_706_p2;
        bias_conv3_load_reg_1194 <= bias_conv3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_700_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        and_ln39_reg_1214 <= and_ln39_fu_790_p2;
        icmp_ln40_reg_1207 <= icmp_ln40_fu_712_p2;
        select_ln39_8_reg_1220 <= select_ln39_8_fu_796_p3;
        select_ln40_7_reg_1275 <= select_ln40_7_fu_940_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_23_reg_1183 <= empty_23_fu_652_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_2_reg_1341 <= icmp_ln42_2_fu_995_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln64_reg_1400 <= icmp_ln64_fu_1061_p2;
        icmp_ln64_reg_1400_pp1_iter1_reg <= icmp_ln64_reg_1400;
        p_cast_reg_1409_pp1_iter1_reg[2 : 0] <= p_cast_reg_1409[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln64_reg_1400_pp1_iter10_reg <= icmp_ln64_reg_1400_pp1_iter9_reg;
        icmp_ln64_reg_1400_pp1_iter11_reg <= icmp_ln64_reg_1400_pp1_iter10_reg;
        icmp_ln64_reg_1400_pp1_iter12_reg <= icmp_ln64_reg_1400_pp1_iter11_reg;
        icmp_ln64_reg_1400_pp1_iter13_reg <= icmp_ln64_reg_1400_pp1_iter12_reg;
        icmp_ln64_reg_1400_pp1_iter14_reg <= icmp_ln64_reg_1400_pp1_iter13_reg;
        icmp_ln64_reg_1400_pp1_iter15_reg <= icmp_ln64_reg_1400_pp1_iter14_reg;
        icmp_ln64_reg_1400_pp1_iter16_reg <= icmp_ln64_reg_1400_pp1_iter15_reg;
        icmp_ln64_reg_1400_pp1_iter17_reg <= icmp_ln64_reg_1400_pp1_iter16_reg;
        icmp_ln64_reg_1400_pp1_iter18_reg <= icmp_ln64_reg_1400_pp1_iter17_reg;
        icmp_ln64_reg_1400_pp1_iter19_reg <= icmp_ln64_reg_1400_pp1_iter18_reg;
        icmp_ln64_reg_1400_pp1_iter20_reg <= icmp_ln64_reg_1400_pp1_iter19_reg;
        icmp_ln64_reg_1400_pp1_iter21_reg <= icmp_ln64_reg_1400_pp1_iter20_reg;
        icmp_ln64_reg_1400_pp1_iter22_reg <= icmp_ln64_reg_1400_pp1_iter21_reg;
        icmp_ln64_reg_1400_pp1_iter23_reg <= icmp_ln64_reg_1400_pp1_iter22_reg;
        icmp_ln64_reg_1400_pp1_iter24_reg <= icmp_ln64_reg_1400_pp1_iter23_reg;
        icmp_ln64_reg_1400_pp1_iter25_reg <= icmp_ln64_reg_1400_pp1_iter24_reg;
        icmp_ln64_reg_1400_pp1_iter26_reg <= icmp_ln64_reg_1400_pp1_iter25_reg;
        icmp_ln64_reg_1400_pp1_iter27_reg <= icmp_ln64_reg_1400_pp1_iter26_reg;
        icmp_ln64_reg_1400_pp1_iter28_reg <= icmp_ln64_reg_1400_pp1_iter27_reg;
        icmp_ln64_reg_1400_pp1_iter29_reg <= icmp_ln64_reg_1400_pp1_iter28_reg;
        icmp_ln64_reg_1400_pp1_iter2_reg <= icmp_ln64_reg_1400_pp1_iter1_reg;
        icmp_ln64_reg_1400_pp1_iter30_reg <= icmp_ln64_reg_1400_pp1_iter29_reg;
        icmp_ln64_reg_1400_pp1_iter31_reg <= icmp_ln64_reg_1400_pp1_iter30_reg;
        icmp_ln64_reg_1400_pp1_iter32_reg <= icmp_ln64_reg_1400_pp1_iter31_reg;
        icmp_ln64_reg_1400_pp1_iter33_reg <= icmp_ln64_reg_1400_pp1_iter32_reg;
        icmp_ln64_reg_1400_pp1_iter34_reg <= icmp_ln64_reg_1400_pp1_iter33_reg;
        icmp_ln64_reg_1400_pp1_iter35_reg <= icmp_ln64_reg_1400_pp1_iter34_reg;
        icmp_ln64_reg_1400_pp1_iter36_reg <= icmp_ln64_reg_1400_pp1_iter35_reg;
        icmp_ln64_reg_1400_pp1_iter37_reg <= icmp_ln64_reg_1400_pp1_iter36_reg;
        icmp_ln64_reg_1400_pp1_iter38_reg <= icmp_ln64_reg_1400_pp1_iter37_reg;
        icmp_ln64_reg_1400_pp1_iter39_reg <= icmp_ln64_reg_1400_pp1_iter38_reg;
        icmp_ln64_reg_1400_pp1_iter3_reg <= icmp_ln64_reg_1400_pp1_iter2_reg;
        icmp_ln64_reg_1400_pp1_iter40_reg <= icmp_ln64_reg_1400_pp1_iter39_reg;
        icmp_ln64_reg_1400_pp1_iter41_reg <= icmp_ln64_reg_1400_pp1_iter40_reg;
        icmp_ln64_reg_1400_pp1_iter42_reg <= icmp_ln64_reg_1400_pp1_iter41_reg;
        icmp_ln64_reg_1400_pp1_iter43_reg <= icmp_ln64_reg_1400_pp1_iter42_reg;
        icmp_ln64_reg_1400_pp1_iter44_reg <= icmp_ln64_reg_1400_pp1_iter43_reg;
        icmp_ln64_reg_1400_pp1_iter45_reg <= icmp_ln64_reg_1400_pp1_iter44_reg;
        icmp_ln64_reg_1400_pp1_iter4_reg <= icmp_ln64_reg_1400_pp1_iter3_reg;
        icmp_ln64_reg_1400_pp1_iter5_reg <= icmp_ln64_reg_1400_pp1_iter4_reg;
        icmp_ln64_reg_1400_pp1_iter6_reg <= icmp_ln64_reg_1400_pp1_iter5_reg;
        icmp_ln64_reg_1400_pp1_iter7_reg <= icmp_ln64_reg_1400_pp1_iter6_reg;
        icmp_ln64_reg_1400_pp1_iter8_reg <= icmp_ln64_reg_1400_pp1_iter7_reg;
        icmp_ln64_reg_1400_pp1_iter9_reg <= icmp_ln64_reg_1400_pp1_iter8_reg;
        line_buffer_0_5_load_2_reg_1420_pp1_iter2_reg <= line_buffer_0_5_load_2_reg_1420;
        line_buffer_1_5_load_3_reg_1456_pp1_iter14_reg <= line_buffer_1_5_load_3_reg_1456;
        line_buffer_2_5_load_3_reg_1497_pp1_iter26_reg <= line_buffer_2_5_load_3_reg_1497;
        mul_0_1_reg_1431_pp1_iter6_reg <= mul_0_1_reg_1431;
        mul_0_1_reg_1431_pp1_iter7_reg <= mul_0_1_reg_1431_pp1_iter6_reg;
        mul_0_1_reg_1431_pp1_iter8_reg <= mul_0_1_reg_1431_pp1_iter7_reg;
        mul_0_2_reg_1436_pp1_iter10_reg <= mul_0_2_reg_1436_pp1_iter9_reg;
        mul_0_2_reg_1436_pp1_iter11_reg <= mul_0_2_reg_1436_pp1_iter10_reg;
        mul_0_2_reg_1436_pp1_iter12_reg <= mul_0_2_reg_1436_pp1_iter11_reg;
        mul_0_2_reg_1436_pp1_iter7_reg <= mul_0_2_reg_1436;
        mul_0_2_reg_1436_pp1_iter8_reg <= mul_0_2_reg_1436_pp1_iter7_reg;
        mul_0_2_reg_1436_pp1_iter9_reg <= mul_0_2_reg_1436_pp1_iter8_reg;
        mul_1_1_reg_1472_pp1_iter18_reg <= mul_1_1_reg_1472;
        mul_1_1_reg_1472_pp1_iter19_reg <= mul_1_1_reg_1472_pp1_iter18_reg;
        mul_1_1_reg_1472_pp1_iter20_reg <= mul_1_1_reg_1472_pp1_iter19_reg;
        mul_1_2_reg_1477_pp1_iter19_reg <= mul_1_2_reg_1477;
        mul_1_2_reg_1477_pp1_iter20_reg <= mul_1_2_reg_1477_pp1_iter19_reg;
        mul_1_2_reg_1477_pp1_iter21_reg <= mul_1_2_reg_1477_pp1_iter20_reg;
        mul_1_2_reg_1477_pp1_iter22_reg <= mul_1_2_reg_1477_pp1_iter21_reg;
        mul_1_2_reg_1477_pp1_iter23_reg <= mul_1_2_reg_1477_pp1_iter22_reg;
        mul_1_2_reg_1477_pp1_iter24_reg <= mul_1_2_reg_1477_pp1_iter23_reg;
        mul_2_1_reg_1513_pp1_iter30_reg <= mul_2_1_reg_1513;
        mul_2_1_reg_1513_pp1_iter31_reg <= mul_2_1_reg_1513_pp1_iter30_reg;
        mul_2_1_reg_1513_pp1_iter32_reg <= mul_2_1_reg_1513_pp1_iter31_reg;
        mul_2_2_reg_1518_pp1_iter31_reg <= mul_2_2_reg_1518;
        mul_2_2_reg_1518_pp1_iter32_reg <= mul_2_2_reg_1518_pp1_iter31_reg;
        mul_2_2_reg_1518_pp1_iter33_reg <= mul_2_2_reg_1518_pp1_iter32_reg;
        mul_2_2_reg_1518_pp1_iter34_reg <= mul_2_2_reg_1518_pp1_iter33_reg;
        mul_2_2_reg_1518_pp1_iter35_reg <= mul_2_2_reg_1518_pp1_iter34_reg;
        mul_2_2_reg_1518_pp1_iter36_reg <= mul_2_2_reg_1518_pp1_iter35_reg;
        p_cast_reg_1409_pp1_iter10_reg[2 : 0] <= p_cast_reg_1409_pp1_iter9_reg[2 : 0];
        p_cast_reg_1409_pp1_iter11_reg[2 : 0] <= p_cast_reg_1409_pp1_iter10_reg[2 : 0];
        p_cast_reg_1409_pp1_iter12_reg[2 : 0] <= p_cast_reg_1409_pp1_iter11_reg[2 : 0];
        p_cast_reg_1409_pp1_iter13_reg[2 : 0] <= p_cast_reg_1409_pp1_iter12_reg[2 : 0];
        p_cast_reg_1409_pp1_iter14_reg[2 : 0] <= p_cast_reg_1409_pp1_iter13_reg[2 : 0];
        p_cast_reg_1409_pp1_iter15_reg[2 : 0] <= p_cast_reg_1409_pp1_iter14_reg[2 : 0];
        p_cast_reg_1409_pp1_iter16_reg[2 : 0] <= p_cast_reg_1409_pp1_iter15_reg[2 : 0];
        p_cast_reg_1409_pp1_iter17_reg[2 : 0] <= p_cast_reg_1409_pp1_iter16_reg[2 : 0];
        p_cast_reg_1409_pp1_iter18_reg[2 : 0] <= p_cast_reg_1409_pp1_iter17_reg[2 : 0];
        p_cast_reg_1409_pp1_iter19_reg[2 : 0] <= p_cast_reg_1409_pp1_iter18_reg[2 : 0];
        p_cast_reg_1409_pp1_iter20_reg[2 : 0] <= p_cast_reg_1409_pp1_iter19_reg[2 : 0];
        p_cast_reg_1409_pp1_iter21_reg[2 : 0] <= p_cast_reg_1409_pp1_iter20_reg[2 : 0];
        p_cast_reg_1409_pp1_iter22_reg[2 : 0] <= p_cast_reg_1409_pp1_iter21_reg[2 : 0];
        p_cast_reg_1409_pp1_iter23_reg[2 : 0] <= p_cast_reg_1409_pp1_iter22_reg[2 : 0];
        p_cast_reg_1409_pp1_iter2_reg[2 : 0] <= p_cast_reg_1409_pp1_iter1_reg[2 : 0];
        p_cast_reg_1409_pp1_iter3_reg[2 : 0] <= p_cast_reg_1409_pp1_iter2_reg[2 : 0];
        p_cast_reg_1409_pp1_iter4_reg[2 : 0] <= p_cast_reg_1409_pp1_iter3_reg[2 : 0];
        p_cast_reg_1409_pp1_iter5_reg[2 : 0] <= p_cast_reg_1409_pp1_iter4_reg[2 : 0];
        p_cast_reg_1409_pp1_iter6_reg[2 : 0] <= p_cast_reg_1409_pp1_iter5_reg[2 : 0];
        p_cast_reg_1409_pp1_iter7_reg[2 : 0] <= p_cast_reg_1409_pp1_iter6_reg[2 : 0];
        p_cast_reg_1409_pp1_iter8_reg[2 : 0] <= p_cast_reg_1409_pp1_iter7_reg[2 : 0];
        p_cast_reg_1409_pp1_iter9_reg[2 : 0] <= p_cast_reg_1409_pp1_iter8_reg[2 : 0];
        sum_reg_1538_pp1_iter45_reg <= sum_reg_1538;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_fu_995_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_cast4_reg_1350[2 : 0] <= j_cast4_fu_1006_p1[2 : 0];
        line_buffer_1_5_addr_reg_1355 <= j_cast4_fu_1006_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        kernel_conv3_load_1_reg_1296 <= kernel_conv3_q1;
        kernel_conv3_load_2_reg_1301 <= kernel_conv3_q2;
        kernel_conv3_load_3_reg_1306 <= kernel_conv3_q3;
        kernel_conv3_load_4_reg_1311 <= kernel_conv3_q4;
        kernel_conv3_load_5_reg_1316 <= kernel_conv3_q5;
        kernel_conv3_load_6_reg_1321 <= kernel_conv3_q6;
        kernel_conv3_load_7_reg_1326 <= kernel_conv3_q7;
        kernel_conv3_load_8_reg_1331 <= kernel_conv3_q8;
        kernel_conv3_load_reg_1291 <= kernel_conv3_q0;
        select_ln40_5_reg_1286 <= select_ln40_5_fu_966_p3;
        select_ln40_reg_1280 <= select_ln40_fu_958_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_0_5_load_2_reg_1420 <= line_buffer_0_5_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter12_reg == 1'd0) & (ap_enable_reg_pp1_iter13 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_1_5_load_3_reg_1456 <= line_buffer_1_5_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter24_reg == 1'd0) & (ap_enable_reg_pp1_iter25 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_2_5_load_3_reg_1497 <= line_buffer_2_5_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_0_1_reg_1431 <= grp_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter5_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_0_2_reg_1436 <= grp_fu_568_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter16_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_1_reg_1472 <= grp_fu_577_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter17_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_2_reg_1477 <= grp_fu_582_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter15_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_reg_1467 <= grp_fu_572_p2;
        sum_4_0_2_reg_1462 <= grp_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter28_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_1_reg_1513 <= grp_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter29_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_2_reg_1518 <= grp_fu_596_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter27_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_reg_1508 <= grp_fu_586_p2;
        sum_4_1_2_reg_1503 <= grp_fu_538_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_reg_1426 <= grp_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1160 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        or_ln45_reg_1336 <= or_ln45_fu_985_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_fu_1061_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_cast_reg_1409[2 : 0] <= p_cast_fu_1082_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter11_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_0_1_reg_1451 <= grp_fu_522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter23_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_1_1_reg_1492 <= grp_fu_534_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter19_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_1_reg_1482 <= grp_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter35_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_2_1_reg_1528 <= grp_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter39_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_2_2_reg_1533 <= grp_fu_550_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter31_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_2_reg_1523 <= grp_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter7_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_4_reg_1441 <= grp_fu_517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1400_pp1_iter43_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_reg_1538 <= grp_fu_554_p2;
    end
end

always @ (*) begin
    if ((icmp_ln42_2_fu_995_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter24 == 1'b0) & (ap_enable_reg_pp1_iter25 == 1'b1))) begin
        ap_condition_pp1_exit_iter25_state34 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter25_state34 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln64_fu_1061_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_700_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter46 == 1'b0) & (ap_enable_reg_pp1_iter45 == 1'b0) & (ap_enable_reg_pp1_iter44 == 1'b0) & (ap_enable_reg_pp1_iter43 == 1'b0) & (ap_enable_reg_pp1_iter42 == 1'b0) & (ap_enable_reg_pp1_iter41 == 1'b0) & (ap_enable_reg_pp1_iter40 == 1'b0) & (ap_enable_reg_pp1_iter39 == 1'b0) & (ap_enable_reg_pp1_iter38 == 1'b0) & (ap_enable_reg_pp1_iter37 == 1'b0) & (ap_enable_reg_pp1_iter36 == 1'b0) & (ap_enable_reg_pp1_iter35 == 1'b0) & (ap_enable_reg_pp1_iter34 == 1'b0) & (ap_enable_reg_pp1_iter33 == 1'b0) & (ap_enable_reg_pp1_iter32 == 1'b0) & (ap_enable_reg_pp1_iter31 == 1'b0) & (ap_enable_reg_pp1_iter30 == 1'b0) & (ap_enable_reg_pp1_iter29 == 1'b0) & (ap_enable_reg_pp1_iter28 == 1'b0) & (ap_enable_reg_pp1_iter27 == 1'b0) & (ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (ap_enable_reg_pp1_iter23 == 1'b0) & (ap_enable_reg_pp1_iter22 == 1'b0) & (ap_enable_reg_pp1_iter21 == 1'b0) & (ap_enable_reg_pp1_iter20 == 1'b0) & (ap_enable_reg_pp1_iter19 == 1'b0) & (ap_enable_reg_pp1_iter18 == 1'b0) & (ap_enable_reg_pp1_iter17 == 1'b0) & (ap_enable_reg_pp1_iter16 == 1'b0) & (ap_enable_reg_pp1_iter15 == 1'b0) & (ap_enable_reg_pp1_iter14 == 1'b0) & (ap_enable_reg_pp1_iter12 == 1'b0) & (ap_enable_reg_pp1_iter11 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter25 == 1'b0) & (ap_enable_reg_pp1_iter13 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1400_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_0_phi_fu_467_p4 = window_buffer_load_3_0_reg_454;
    end else begin
        ap_phi_mux_window_buffer_load_0_phi_fu_467_p4 = window_buffer_load_0_reg_464;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1400_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_1_phi_fu_488_p4 = window_buffer_load_3_1_reg_475;
    end else begin
        ap_phi_mux_window_buffer_load_1_phi_fu_488_p4 = window_buffer_load_1_reg_485;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1400_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_2_phi_fu_509_p4 = window_buffer_load_3_2_reg_496;
    end else begin
        ap_phi_mux_window_buffer_load_2_phi_fu_509_p4 = window_buffer_load_2_reg_506;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_700_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_conv3_address0 = zext_ln40_10_fu_810_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bias_conv3_address0 = zext_ln40_fu_647_p1;
    end else begin
        bias_conv3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        bias_conv3_ce0 = 1'b1;
    end else begin
        bias_conv3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce0 = 1'b1;
    end else begin
        kernel_conv3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce1 = 1'b1;
    end else begin
        kernel_conv3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce2 = 1'b1;
    end else begin
        kernel_conv3_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce3 = 1'b1;
    end else begin
        kernel_conv3_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce4 = 1'b1;
    end else begin
        kernel_conv3_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce5 = 1'b1;
    end else begin
        kernel_conv3_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce6 = 1'b1;
    end else begin
        kernel_conv3_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce7 = 1'b1;
    end else begin
        kernel_conv3_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv3_ce8 = 1'b1;
    end else begin
        kernel_conv3_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_0_5_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_5_address0 = j_cast4_reg_1350;
    end else begin
        line_buffer_0_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line_buffer_0_5_address1 = p_cast_fu_1082_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_0_5_address1 = 3'd1;
    end else begin
        line_buffer_0_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_0_5_ce0 = 1'b1;
    end else begin
        line_buffer_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_0_5_ce1 = 1'b1;
    end else begin
        line_buffer_0_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_reg_1341 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_5_we0 = 1'b1;
    end else begin
        line_buffer_0_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter12 == 1'b1))) begin
        line_buffer_1_5_address0 = p_cast_reg_1409_pp1_iter11_reg;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_1_5_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_5_address0 = j_cast4_fu_1006_p1;
    end else begin
        line_buffer_1_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_1_5_address1 = 3'd1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_5_address1 = line_buffer_1_5_addr_reg_1355;
    end else begin
        line_buffer_1_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp1_iter12 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_1_5_ce0 = 1'b1;
    end else begin
        line_buffer_1_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_1_5_ce1 = 1'b1;
    end else begin
        line_buffer_1_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_reg_1341 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_5_we1 = 1'b1;
    end else begin
        line_buffer_1_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_2_5_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln42_2_fu_995_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_2_5_address0 = j_cast4_fu_1006_p1;
    end else begin
        line_buffer_2_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter24 == 1'b1))) begin
        line_buffer_2_5_address1 = p_cast_reg_1409_pp1_iter23_reg;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_2_5_address1 = 3'd1;
    end else begin
        line_buffer_2_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_fu_995_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_2_5_ce0 = 1'b1;
    end else begin
        line_buffer_2_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter24 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_2_5_ce1 = 1'b1;
    end else begin
        line_buffer_2_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_2_fu_995_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_2_5_we0 = 1'b1;
    end else begin
        line_buffer_2_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln64_reg_1400_pp1_iter45_reg == 1'd0) & (ap_enable_reg_pp1_iter46 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_conv3_ap_vld = 1'b1;
    end else begin
        output_conv3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln39_fu_700_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln42_reg_1160 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln42_2_fu_995_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln42_2_fu_995_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln52_fu_1051_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((cmp4827_reg_1174 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter25 == 1'b1)) & ~((ap_enable_reg_pp1_iter45 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter46 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter45 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter46 == 1'b1)) | ((ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter25 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln83_4_fu_672_p0 = num_channel_reg_397;

assign add_ln83_4_fu_672_p1 = {{empty_fu_660_p1}, {3'd0}};

assign add_ln83_5_fu_748_p0 = add_ln39_2_fu_726_p2;

assign add_ln83_5_fu_748_p1 = {{empty_29_fu_736_p1}, {3'd0}};

assign add_ln83_6_fu_833_p0 = select_ln39_5_fu_758_p3;

assign add_ln83_6_fu_833_p1 = tmp_mid1_fu_819_p4;

assign add_ln83_fu_694_p0 = add_ln83_4_fu_672_p2;

assign add_ln83_fu_694_p1 = tmp_fu_682_p4;

assign and_ln11_fu_1122_p2 = (or_ln11_fu_1116_p2 & grp_fu_600_p2);

assign and_ln39_fu_790_p2 = (xor_ln39_fu_778_p2 & icmp_ln41_fu_784_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp1_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp1_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp1_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp1_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp1_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp1_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp1_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp1_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp1_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp1_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp1_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp1_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp1_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp1_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp1_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp1_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp1_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp1_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp1_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp1_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp1_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp1_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp1_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp1_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp1_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp1_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign b_cast_fu_1057_p1 = b_reg_443;

assign bitcast_ln11_fu_1087_p1 = sum_reg_1538_pp1_iter45_reg;

assign bitcast_ln49_fu_643_p1 = p_read;

assign cmp4827_fu_637_p2 = (($signed(sub47_fu_631_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_23_fu_652_p1 = num_ker_reg_374[2:0];

assign empty_27_fu_1076_p1 = b_reg_443[2:0];

assign empty_29_fu_736_p1 = add_ln39_2_fu_726_p2[2:0];

assign empty_30_fu_815_p1 = add_ln40_fu_804_p2[2:0];

assign empty_fu_660_p1 = num_channel_reg_397[2:0];

assign icmp_ln11_2_fu_1110_p2 = ((trunc_ln11_fu_1100_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_1104_p2 = ((tmp_5_fu_1090_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_700_p2 = ((indvar_flatten109_reg_386 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_712_p2 = ((indvar_flatten_reg_408 == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_784_p2 = ((i_reg_420 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln42_2_fu_995_p2 = ((j_cast_fu_991_p1 == add_ln31_reg_1155) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_619_p2 = (($signed(add_ln31_fu_613_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_1018_p2 = ((j_cast_fu_991_p1 == sub13_reg_1164) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_973_p2 = ((select_ln40_fu_958_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_979_p2 = ((select_ln40_fu_958_p3 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1012_p2 = ((j_reg_432 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1051_p2 = ((tmp_2_fu_1042_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_1061_p2 = ((b_cast_fu_1057_p1 == sub47_reg_1169) ? 1'b1 : 1'b0);

assign j_cast4_fu_1006_p1 = j_reg_432;

assign j_cast_fu_991_p1 = j_reg_432;

assign kernel_conv3_address0 = zext_ln83_8_fu_847_p1;

assign kernel_conv3_address1 = zext_ln40_11_fu_858_p1;

assign kernel_conv3_address2 = zext_ln40_12_fu_869_p1;

assign kernel_conv3_address3 = zext_ln40_13_fu_880_p1;

assign kernel_conv3_address4 = zext_ln40_14_fu_891_p1;

assign kernel_conv3_address5 = zext_ln40_15_fu_902_p1;

assign kernel_conv3_address6 = zext_ln40_16_fu_913_p1;

assign kernel_conv3_address7 = zext_ln40_17_fu_924_p1;

assign kernel_conv3_address8 = zext_ln40_18_fu_935_p1;

assign line_buffer_2_5_d0 = ((or_ln45_4_fu_1029_p2[0:0] === 1'b1) ? 64'd0 : bitcast_ln49_reg_1178);

assign or_ln11_fu_1116_p2 = (icmp_ln11_fu_1104_p2 | icmp_ln11_2_fu_1110_p2);

assign or_ln40_fu_954_p2 = (icmp_ln40_reg_1207 | and_ln39_reg_1214);

assign or_ln45_3_fu_1023_p2 = (icmp_ln45_fu_1012_p2 | icmp_ln45_2_fu_1018_p2);

assign or_ln45_4_fu_1029_p2 = (or_ln45_reg_1336 | or_ln45_3_fu_1023_p2);

assign or_ln45_fu_985_p2 = (icmp_ln45_5_fu_979_p2 | icmp_ln45_4_fu_973_p2);

assign output_conv3 = ((and_ln11_fu_1122_p2[0:0] === 1'b1) ? bitcast_ln11_fu_1087_p1 : 64'd0);

assign p_cast_fu_1082_p1 = empty_27_fu_1076_p2;

assign select_ln39_5_fu_758_p3 = ((icmp_ln40_fu_712_p2[0:0] === 1'b1) ? add_ln83_5_fu_748_p2 : add_ln83_4_fu_672_p2);

assign select_ln39_6_fu_948_p3 = ((icmp_ln40_reg_1207[0:0] === 1'b1) ? 64'd13815139047020317846 : bias_conv3_load_reg_1194);

assign select_ln39_7_fu_770_p3 = ((icmp_ln40_fu_712_p2[0:0] === 1'b1) ? zext_ln83_6_fu_754_p1 : add_ln83_fu_694_p2);

assign select_ln39_8_fu_796_p3 = ((icmp_ln40_fu_712_p2[0:0] === 1'b1) ? add_ln39_2_fu_726_p2 : num_channel_reg_397);

assign select_ln39_fu_718_p3 = ((icmp_ln40_fu_712_p2[0:0] === 1'b1) ? 4'd0 : num_ker_reg_374);

assign select_ln40_5_fu_966_p3 = ((and_ln39_reg_1214[0:0] === 1'b1) ? bias_conv3_q0 : select_ln39_6_fu_948_p3);

assign select_ln40_6_fu_839_p3 = ((and_ln39_fu_790_p2[0:0] === 1'b1) ? add_ln83_6_fu_833_p2 : select_ln39_7_fu_770_p3);

assign select_ln40_7_fu_940_p3 = ((and_ln39_fu_790_p2[0:0] === 1'b1) ? add_ln40_fu_804_p2 : select_ln39_fu_718_p3);

assign select_ln40_8_fu_1148_p3 = ((icmp_ln40_reg_1207[0:0] === 1'b1) ? 8'd1 : add_ln40_18_fu_1142_p2);

assign select_ln40_fu_958_p3 = ((or_ln40_fu_954_p2[0:0] === 1'b1) ? 4'd0 : i_reg_420);

assign shl_ln_fu_605_p3 = {{padding}, {1'd0}};

assign tmp_2_fu_1042_p4 = {{select_ln40_reg_1280[3:1]}};

assign tmp_5_fu_1090_p4 = {{bitcast_ln11_fu_1087_p1[62:52]}};

assign tmp_fu_682_p4 = {{{empty_23_reg_1183}, {empty_23_reg_1183}}, {3'd0}};

assign tmp_mid1_fu_819_p4 = {{{empty_30_fu_815_p1}, {empty_30_fu_815_p1}}, {3'd0}};

assign trunc_ln11_fu_1100_p1 = bitcast_ln11_fu_1087_p1[51:0];

assign xor_ln39_fu_778_p2 = (icmp_ln40_fu_712_p2 ^ 1'd1);

assign zext_ln40_10_fu_810_p1 = add_ln40_fu_804_p2;

assign zext_ln40_11_fu_858_p1 = add_ln40_10_fu_852_p2;

assign zext_ln40_12_fu_869_p1 = add_ln40_11_fu_863_p2;

assign zext_ln40_13_fu_880_p1 = add_ln40_12_fu_874_p2;

assign zext_ln40_14_fu_891_p1 = add_ln40_13_fu_885_p2;

assign zext_ln40_15_fu_902_p1 = add_ln40_14_fu_896_p2;

assign zext_ln40_16_fu_913_p1 = add_ln40_15_fu_907_p2;

assign zext_ln40_17_fu_924_p1 = add_ln40_16_fu_918_p2;

assign zext_ln40_18_fu_935_p1 = add_ln40_17_fu_929_p2;

assign zext_ln40_fu_647_p1 = num_ker_reg_374;

assign zext_ln83_6_fu_754_p1 = add_ln83_5_fu_748_p2;

assign zext_ln83_8_fu_847_p1 = select_ln40_6_fu_839_p3;

always @ (posedge ap_clk) begin
    j_cast4_reg_1350[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter5_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter6_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter7_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter8_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter9_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter10_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter11_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter12_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter13_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter14_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter15_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter16_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter17_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter18_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter19_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter20_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter21_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter22_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1409_pp1_iter23_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //CNN_convolution_double_double_double_double_7_7_8_8_7_7_3_3_1_1_s
