// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        output_conv5,
        output_conv5_ap_vld,
        padding
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_pp0_stage0 = 9'd16;
parameter    ap_ST_fsm_state7 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_pp1_stage0 = 9'd128;
parameter    ap_ST_fsm_state56 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] p_read;
output  [63:0] output_conv5;
output   output_conv5_ap_vld;
input  [30:0] padding;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_conv5_ap_vld;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] bias_conv5_address0;
reg    bias_conv5_ce0;
wire   [63:0] bias_conv5_q0;
reg   [2:0] line_buffer_1_address0;
reg    line_buffer_1_ce0;
wire   [63:0] line_buffer_1_q0;
reg   [2:0] line_buffer_1_address1;
reg    line_buffer_1_ce1;
reg    line_buffer_1_we1;
wire   [63:0] line_buffer_1_q1;
reg   [2:0] line_buffer_0_address0;
reg    line_buffer_0_ce0;
reg    line_buffer_0_we0;
wire   [63:0] line_buffer_0_q0;
reg   [2:0] line_buffer_0_address1;
reg    line_buffer_0_ce1;
wire   [63:0] line_buffer_0_q1;
reg   [2:0] line_buffer_2_address0;
reg    line_buffer_2_ce0;
reg    line_buffer_2_we0;
wire   [63:0] line_buffer_2_d0;
wire   [63:0] line_buffer_2_q0;
reg   [2:0] line_buffer_2_address1;
reg    line_buffer_2_ce1;
wire   [63:0] line_buffer_2_q1;
wire   [9:0] kernel_conv5_address0;
reg    kernel_conv5_ce0;
wire   [63:0] kernel_conv5_q0;
wire   [9:0] kernel_conv5_address1;
reg    kernel_conv5_ce1;
wire   [63:0] kernel_conv5_q1;
wire   [9:0] kernel_conv5_address2;
reg    kernel_conv5_ce2;
wire   [63:0] kernel_conv5_q2;
wire   [9:0] kernel_conv5_address3;
reg    kernel_conv5_ce3;
wire   [63:0] kernel_conv5_q3;
wire   [9:0] kernel_conv5_address4;
reg    kernel_conv5_ce4;
wire   [63:0] kernel_conv5_q4;
wire   [9:0] kernel_conv5_address5;
reg    kernel_conv5_ce5;
wire   [63:0] kernel_conv5_q5;
wire   [9:0] kernel_conv5_address6;
reg    kernel_conv5_ce6;
wire   [63:0] kernel_conv5_q6;
wire   [9:0] kernel_conv5_address7;
reg    kernel_conv5_ce7;
wire   [63:0] kernel_conv5_q7;
wire   [9:0] kernel_conv5_address8;
reg    kernel_conv5_ce8;
wire   [63:0] kernel_conv5_q8;
reg   [3:0] j_reg_430;
reg   [30:0] b_reg_441;
reg   [63:0] window_buffer_load_1_0_reg_452;
wire    ap_block_state9_pp1_stage0_iter0;
wire    ap_block_state10_pp1_stage0_iter1;
wire    ap_block_state11_pp1_stage0_iter2;
wire    ap_block_state12_pp1_stage0_iter3;
wire    ap_block_state13_pp1_stage0_iter4;
wire    ap_block_state14_pp1_stage0_iter5;
wire    ap_block_state15_pp1_stage0_iter6;
wire    ap_block_state16_pp1_stage0_iter7;
wire    ap_block_state17_pp1_stage0_iter8;
wire    ap_block_state18_pp1_stage0_iter9;
wire    ap_block_state19_pp1_stage0_iter10;
wire    ap_block_state20_pp1_stage0_iter11;
wire    ap_block_state21_pp1_stage0_iter12;
wire    ap_block_state22_pp1_stage0_iter13;
wire    ap_block_state23_pp1_stage0_iter14;
wire    ap_block_state24_pp1_stage0_iter15;
wire    ap_block_state25_pp1_stage0_iter16;
wire    ap_block_state26_pp1_stage0_iter17;
wire    ap_block_state27_pp1_stage0_iter18;
wire    ap_block_state28_pp1_stage0_iter19;
wire    ap_block_state29_pp1_stage0_iter20;
wire    ap_block_state30_pp1_stage0_iter21;
wire    ap_block_state31_pp1_stage0_iter22;
wire    ap_block_state32_pp1_stage0_iter23;
wire    ap_block_state33_pp1_stage0_iter24;
wire    ap_block_state34_pp1_stage0_iter25;
wire    ap_block_state35_pp1_stage0_iter26;
wire    ap_block_state36_pp1_stage0_iter27;
wire    ap_block_state37_pp1_stage0_iter28;
wire    ap_block_state38_pp1_stage0_iter29;
wire    ap_block_state39_pp1_stage0_iter30;
wire    ap_block_state40_pp1_stage0_iter31;
wire    ap_block_state41_pp1_stage0_iter32;
wire    ap_block_state42_pp1_stage0_iter33;
wire    ap_block_state43_pp1_stage0_iter34;
wire    ap_block_state44_pp1_stage0_iter35;
wire    ap_block_state45_pp1_stage0_iter36;
wire    ap_block_state46_pp1_stage0_iter37;
wire    ap_block_state47_pp1_stage0_iter38;
wire    ap_block_state48_pp1_stage0_iter39;
wire    ap_block_state49_pp1_stage0_iter40;
wire    ap_block_state50_pp1_stage0_iter41;
wire    ap_block_state51_pp1_stage0_iter42;
wire    ap_block_state52_pp1_stage0_iter43;
wire    ap_block_state53_pp1_stage0_iter44;
wire    ap_block_state54_pp1_stage0_iter45;
wire    ap_block_state55_pp1_stage0_iter46;
wire    ap_block_pp1_stage0_11001;
reg   [63:0] window_buffer_load_0_reg_462;
reg   [63:0] window_buffer_load_1_1_reg_473;
reg   [63:0] window_buffer_load_15_reg_483;
reg   [63:0] window_buffer_load_1_2_reg_494;
reg   [63:0] window_buffer_load_26_reg_504;
wire   [31:0] add_ln31_fu_611_p2;
reg   [31:0] add_ln31_reg_1153;
wire   [0:0] icmp_ln42_fu_617_p2;
reg   [0:0] icmp_ln42_reg_1158;
wire   [31:0] sub13_fu_623_p2;
reg   [31:0] sub13_reg_1162;
wire   [31:0] sub47_fu_629_p2;
reg   [31:0] sub47_reg_1167;
wire   [0:0] cmp4827_fu_635_p2;
reg   [0:0] cmp4827_reg_1172;
wire   [63:0] bitcast_ln49_fu_641_p1;
reg   [63:0] bitcast_ln49_reg_1176;
wire   [2:0] empty_15_fu_650_p1;
reg   [2:0] empty_15_reg_1181;
wire    ap_CS_fsm_state2;
reg   [63:0] bias_conv5_load_reg_1192;
wire    ap_CS_fsm_state3;
wire   [9:0] add_ln39_fu_704_p2;
reg   [9:0] add_ln39_reg_1200;
wire   [0:0] icmp_ln40_fu_710_p2;
reg   [0:0] icmp_ln40_reg_1205;
wire   [0:0] icmp_ln39_fu_698_p2;
wire   [0:0] and_ln39_fu_788_p2;
reg   [0:0] and_ln39_reg_1212;
wire   [3:0] select_ln39_4_fu_794_p3;
reg   [3:0] select_ln39_4_reg_1218;
wire   [3:0] select_ln40_3_fu_938_p3;
reg   [3:0] select_ln40_3_reg_1273;
wire   [3:0] select_ln40_fu_956_p3;
reg   [3:0] select_ln40_reg_1278;
wire    ap_CS_fsm_state4;
wire   [63:0] select_ln40_1_fu_964_p3;
reg   [63:0] select_ln40_1_reg_1284;
reg   [63:0] kernel_conv5_load_reg_1289;
reg   [63:0] kernel_conv5_load_1_reg_1294;
reg   [63:0] kernel_conv5_load_2_reg_1299;
reg   [63:0] kernel_conv5_load_3_reg_1304;
reg   [63:0] kernel_conv5_load_4_reg_1309;
reg   [63:0] kernel_conv5_load_5_reg_1314;
reg   [63:0] kernel_conv5_load_6_reg_1319;
reg   [63:0] kernel_conv5_load_7_reg_1324;
reg   [63:0] kernel_conv5_load_8_reg_1329;
wire   [0:0] or_ln45_fu_983_p2;
reg   [0:0] or_ln45_reg_1334;
wire   [0:0] icmp_ln42_1_fu_993_p2;
reg   [0:0] icmp_ln42_1_reg_1339;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln42_fu_998_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] j_cast4_fu_1004_p1;
reg   [63:0] j_cast4_reg_1348;
reg   [2:0] line_buffer_1_addr_reg_1353;
wire   [0:0] icmp_ln52_fu_1049_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln64_fu_1059_p2;
reg   [0:0] icmp_ln64_reg_1398;
wire    ap_CS_fsm_pp1_stage0;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter1_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter2_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter3_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter4_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter5_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter6_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter7_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter8_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter9_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter10_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter11_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter12_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter13_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter14_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter15_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter16_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter17_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter18_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter19_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter20_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter21_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter22_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter23_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter24_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter25_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter26_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter27_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter28_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter29_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter30_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter31_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter32_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter33_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter34_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter35_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter36_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter37_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter38_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter39_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter40_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter41_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter42_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter43_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter44_reg;
reg   [0:0] icmp_ln64_reg_1398_pp1_iter45_reg;
wire   [30:0] add_ln64_fu_1064_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [63:0] p_cast_fu_1080_p1;
reg   [63:0] p_cast_reg_1407;
reg   [63:0] p_cast_reg_1407_pp1_iter1_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter2_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter3_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter4_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter5_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter6_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter7_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter8_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter9_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter10_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter11_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter12_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter13_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter14_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter15_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter16_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter17_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter18_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter19_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter20_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter21_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter22_reg;
reg   [63:0] p_cast_reg_1407_pp1_iter23_reg;
reg   [63:0] line_buffer_0_load_2_reg_1418;
reg    ap_enable_reg_pp1_iter1;
reg   [63:0] line_buffer_0_load_2_reg_1418_pp1_iter2_reg;
wire   [63:0] grp_fu_556_p2;
reg   [63:0] mul_reg_1424;
wire   [63:0] grp_fu_561_p2;
reg   [63:0] mul_0_1_reg_1429;
reg   [63:0] mul_0_1_reg_1429_pp1_iter6_reg;
reg   [63:0] mul_0_1_reg_1429_pp1_iter7_reg;
reg   [63:0] mul_0_1_reg_1429_pp1_iter8_reg;
wire   [63:0] grp_fu_566_p2;
reg   [63:0] mul_0_2_reg_1434;
reg   [63:0] mul_0_2_reg_1434_pp1_iter7_reg;
reg   [63:0] mul_0_2_reg_1434_pp1_iter8_reg;
reg   [63:0] mul_0_2_reg_1434_pp1_iter9_reg;
reg   [63:0] mul_0_2_reg_1434_pp1_iter10_reg;
reg   [63:0] mul_0_2_reg_1434_pp1_iter11_reg;
reg   [63:0] mul_0_2_reg_1434_pp1_iter12_reg;
wire   [63:0] grp_fu_515_p2;
reg   [63:0] sum_1_reg_1439;
wire   [63:0] grp_fu_520_p2;
reg   [63:0] sum_1_0_1_reg_1449;
reg   [63:0] line_buffer_1_load_3_reg_1454;
reg    ap_enable_reg_pp1_iter13;
reg   [63:0] line_buffer_1_load_3_reg_1454_pp1_iter14_reg;
wire   [63:0] grp_fu_524_p2;
reg   [63:0] sum_1_0_2_reg_1460;
wire   [63:0] grp_fu_570_p2;
reg   [63:0] mul_1_reg_1465;
wire   [63:0] grp_fu_575_p2;
reg   [63:0] mul_1_1_reg_1470;
reg   [63:0] mul_1_1_reg_1470_pp1_iter18_reg;
reg   [63:0] mul_1_1_reg_1470_pp1_iter19_reg;
reg   [63:0] mul_1_1_reg_1470_pp1_iter20_reg;
wire   [63:0] grp_fu_580_p2;
reg   [63:0] mul_1_2_reg_1475;
reg   [63:0] mul_1_2_reg_1475_pp1_iter19_reg;
reg   [63:0] mul_1_2_reg_1475_pp1_iter20_reg;
reg   [63:0] mul_1_2_reg_1475_pp1_iter21_reg;
reg   [63:0] mul_1_2_reg_1475_pp1_iter22_reg;
reg   [63:0] mul_1_2_reg_1475_pp1_iter23_reg;
reg   [63:0] mul_1_2_reg_1475_pp1_iter24_reg;
wire   [63:0] grp_fu_528_p2;
reg   [63:0] sum_1_1_reg_1480;
wire   [63:0] grp_fu_532_p2;
reg   [63:0] sum_1_1_1_reg_1490;
reg   [63:0] line_buffer_2_load_3_reg_1495;
reg    ap_enable_reg_pp1_iter25;
reg   [63:0] line_buffer_2_load_3_reg_1495_pp1_iter26_reg;
wire   [63:0] grp_fu_536_p2;
reg   [63:0] sum_1_1_2_reg_1501;
wire   [63:0] grp_fu_584_p2;
reg   [63:0] mul_2_reg_1506;
wire   [63:0] grp_fu_589_p2;
reg   [63:0] mul_2_1_reg_1511;
reg   [63:0] mul_2_1_reg_1511_pp1_iter30_reg;
reg   [63:0] mul_2_1_reg_1511_pp1_iter31_reg;
reg   [63:0] mul_2_1_reg_1511_pp1_iter32_reg;
wire   [63:0] grp_fu_594_p2;
reg   [63:0] mul_2_2_reg_1516;
reg   [63:0] mul_2_2_reg_1516_pp1_iter31_reg;
reg   [63:0] mul_2_2_reg_1516_pp1_iter32_reg;
reg   [63:0] mul_2_2_reg_1516_pp1_iter33_reg;
reg   [63:0] mul_2_2_reg_1516_pp1_iter34_reg;
reg   [63:0] mul_2_2_reg_1516_pp1_iter35_reg;
reg   [63:0] mul_2_2_reg_1516_pp1_iter36_reg;
wire   [63:0] grp_fu_540_p2;
reg   [63:0] sum_1_2_reg_1521;
wire   [63:0] grp_fu_544_p2;
reg   [63:0] sum_1_2_1_reg_1526;
wire   [63:0] grp_fu_548_p2;
reg   [63:0] sum_1_2_2_reg_1531;
wire   [63:0] grp_fu_552_p2;
reg   [63:0] sum_reg_1536;
reg   [63:0] sum_reg_1536_pp1_iter45_reg;
wire   [3:0] add_ln41_fu_1135_p2;
wire    ap_CS_fsm_state56;
wire   [7:0] select_ln40_4_fu_1146_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
reg    ap_enable_reg_pp1_iter11;
reg    ap_enable_reg_pp1_iter12;
reg    ap_enable_reg_pp1_iter14;
reg    ap_enable_reg_pp1_iter15;
reg    ap_enable_reg_pp1_iter16;
reg    ap_enable_reg_pp1_iter17;
reg    ap_enable_reg_pp1_iter18;
reg    ap_enable_reg_pp1_iter19;
reg    ap_enable_reg_pp1_iter20;
reg    ap_enable_reg_pp1_iter21;
reg    ap_enable_reg_pp1_iter22;
reg    ap_enable_reg_pp1_iter23;
reg    ap_enable_reg_pp1_iter24;
reg    ap_enable_reg_pp1_iter26;
reg    ap_condition_pp1_exit_iter25_state34;
reg    ap_enable_reg_pp1_iter27;
reg    ap_enable_reg_pp1_iter28;
reg    ap_enable_reg_pp1_iter29;
reg    ap_enable_reg_pp1_iter30;
reg    ap_enable_reg_pp1_iter31;
reg    ap_enable_reg_pp1_iter32;
reg    ap_enable_reg_pp1_iter33;
reg    ap_enable_reg_pp1_iter34;
reg    ap_enable_reg_pp1_iter35;
reg    ap_enable_reg_pp1_iter36;
reg    ap_enable_reg_pp1_iter37;
reg    ap_enable_reg_pp1_iter38;
reg    ap_enable_reg_pp1_iter39;
reg    ap_enable_reg_pp1_iter40;
reg    ap_enable_reg_pp1_iter41;
reg    ap_enable_reg_pp1_iter42;
reg    ap_enable_reg_pp1_iter43;
reg    ap_enable_reg_pp1_iter44;
reg    ap_enable_reg_pp1_iter45;
reg    ap_enable_reg_pp1_iter46;
reg   [3:0] num_ker_reg_372;
reg   [9:0] indvar_flatten109_reg_384;
reg   [3:0] num_channel_reg_395;
reg   [7:0] indvar_flatten_reg_406;
reg   [3:0] i_reg_418;
wire    ap_block_pp1_stage0;
reg   [63:0] ap_phi_mux_window_buffer_load_0_phi_fu_465_p4;
reg   [63:0] ap_phi_mux_window_buffer_load_15_phi_fu_486_p4;
reg   [63:0] ap_phi_mux_window_buffer_load_26_phi_fu_507_p4;
wire   [63:0] zext_ln40_fu_645_p1;
wire   [63:0] zext_ln40_1_fu_808_p1;
wire   [63:0] zext_ln83_4_fu_845_p1;
wire   [63:0] zext_ln40_2_fu_856_p1;
wire   [63:0] zext_ln40_3_fu_867_p1;
wire   [63:0] zext_ln40_4_fu_878_p1;
wire   [63:0] zext_ln40_5_fu_889_p1;
wire   [63:0] zext_ln40_6_fu_900_p1;
wire   [63:0] zext_ln40_7_fu_911_p1;
wire   [63:0] zext_ln40_8_fu_922_p1;
wire   [63:0] zext_ln40_9_fu_933_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp1_stage0_01001;
wire   [31:0] shl_ln_fu_603_p3;
wire   [2:0] empty_fu_658_p1;
wire   [5:0] add_ln83_1_fu_670_p0;
wire   [5:0] add_ln83_1_fu_670_p1;
wire   [5:0] add_ln83_1_fu_670_p2;
wire   [8:0] tmp_fu_680_p4;
wire   [9:0] add_ln83_fu_692_p0;
wire   [9:0] add_ln83_fu_692_p1;
wire   [3:0] add_ln39_1_fu_724_p2;
wire   [2:0] empty_21_fu_734_p1;
wire   [5:0] add_ln83_2_fu_746_p0;
wire   [5:0] add_ln83_2_fu_746_p1;
wire   [5:0] add_ln83_2_fu_746_p2;
wire   [5:0] select_ln39_1_fu_756_p3;
wire   [9:0] zext_ln83_2_fu_752_p1;
wire   [9:0] add_ln83_fu_692_p2;
wire   [0:0] icmp_ln41_fu_782_p2;
wire   [0:0] xor_ln39_fu_776_p2;
wire   [3:0] select_ln39_fu_716_p3;
wire   [3:0] add_ln40_fu_802_p2;
wire   [2:0] empty_22_fu_813_p1;
wire   [8:0] tmp_mid1_fu_817_p4;
wire   [9:0] add_ln83_3_fu_831_p0;
wire   [9:0] add_ln83_3_fu_831_p1;
wire   [9:0] add_ln83_3_fu_831_p2;
wire   [9:0] select_ln39_3_fu_768_p3;
wire   [9:0] select_ln40_2_fu_837_p3;
wire   [9:0] add_ln40_1_fu_850_p2;
wire   [9:0] add_ln40_2_fu_861_p2;
wire   [9:0] add_ln40_3_fu_872_p2;
wire   [9:0] add_ln40_4_fu_883_p2;
wire   [9:0] add_ln40_5_fu_894_p2;
wire   [9:0] add_ln40_6_fu_905_p2;
wire   [9:0] add_ln40_7_fu_916_p2;
wire   [9:0] add_ln40_8_fu_927_p2;
wire   [0:0] or_ln40_fu_952_p2;
wire   [63:0] select_ln39_2_fu_946_p3;
wire   [0:0] icmp_ln45_2_fu_971_p2;
wire   [0:0] icmp_ln45_3_fu_977_p2;
wire   [31:0] j_cast_fu_989_p1;
wire   [0:0] icmp_ln45_1_fu_1016_p2;
wire   [0:0] icmp_ln45_fu_1010_p2;
wire   [0:0] or_ln45_1_fu_1021_p2;
wire   [0:0] or_ln45_2_fu_1027_p2;
wire   [2:0] tmp_1_fu_1040_p4;
wire   [31:0] b_cast_fu_1055_p1;
wire   [2:0] empty_19_fu_1074_p1;
wire   [2:0] empty_19_fu_1074_p2;
wire   [63:0] bitcast_ln11_fu_1085_p1;
wire   [10:0] tmp_2_fu_1088_p4;
wire   [51:0] trunc_ln11_fu_1098_p1;
wire   [0:0] icmp_ln11_1_fu_1108_p2;
wire   [0:0] icmp_ln11_fu_1102_p2;
wire   [0:0] or_ln11_fu_1114_p2;
wire   [0:0] grp_fu_598_p2;
wire   [0:0] and_ln11_fu_1120_p2;
wire   [7:0] add_ln40_9_fu_1140_p2;
wire    ap_block_pp1_stage0_00001;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter13 = 1'b0;
#0 ap_enable_reg_pp1_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter12 = 1'b0;
#0 ap_enable_reg_pp1_iter14 = 1'b0;
#0 ap_enable_reg_pp1_iter15 = 1'b0;
#0 ap_enable_reg_pp1_iter16 = 1'b0;
#0 ap_enable_reg_pp1_iter17 = 1'b0;
#0 ap_enable_reg_pp1_iter18 = 1'b0;
#0 ap_enable_reg_pp1_iter19 = 1'b0;
#0 ap_enable_reg_pp1_iter20 = 1'b0;
#0 ap_enable_reg_pp1_iter21 = 1'b0;
#0 ap_enable_reg_pp1_iter22 = 1'b0;
#0 ap_enable_reg_pp1_iter23 = 1'b0;
#0 ap_enable_reg_pp1_iter24 = 1'b0;
#0 ap_enable_reg_pp1_iter26 = 1'b0;
#0 ap_enable_reg_pp1_iter27 = 1'b0;
#0 ap_enable_reg_pp1_iter28 = 1'b0;
#0 ap_enable_reg_pp1_iter29 = 1'b0;
#0 ap_enable_reg_pp1_iter30 = 1'b0;
#0 ap_enable_reg_pp1_iter31 = 1'b0;
#0 ap_enable_reg_pp1_iter32 = 1'b0;
#0 ap_enable_reg_pp1_iter33 = 1'b0;
#0 ap_enable_reg_pp1_iter34 = 1'b0;
#0 ap_enable_reg_pp1_iter35 = 1'b0;
#0 ap_enable_reg_pp1_iter36 = 1'b0;
#0 ap_enable_reg_pp1_iter37 = 1'b0;
#0 ap_enable_reg_pp1_iter38 = 1'b0;
#0 ap_enable_reg_pp1_iter39 = 1'b0;
#0 ap_enable_reg_pp1_iter40 = 1'b0;
#0 ap_enable_reg_pp1_iter41 = 1'b0;
#0 ap_enable_reg_pp1_iter42 = 1'b0;
#0 ap_enable_reg_pp1_iter43 = 1'b0;
#0 ap_enable_reg_pp1_iter44 = 1'b0;
#0 ap_enable_reg_pp1_iter45 = 1'b0;
#0 ap_enable_reg_pp1_iter46 = 1'b0;
end

CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s_bias_conv5 #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
bias_conv5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_conv5_address0),
    .ce0(bias_conv5_ce0),
    .q0(bias_conv5_q0)
);

CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s_line_buffer_1 #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_address0),
    .ce0(line_buffer_1_ce0),
    .q0(line_buffer_1_q0),
    .address1(line_buffer_1_address1),
    .ce1(line_buffer_1_ce1),
    .we1(line_buffer_1_we1),
    .d1(line_buffer_2_q0),
    .q1(line_buffer_1_q1)
);

CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s_line_buffer_0 #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
line_buffer_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_0_address0),
    .ce0(line_buffer_0_ce0),
    .we0(line_buffer_0_we0),
    .d0(line_buffer_1_q0),
    .q0(line_buffer_0_q0),
    .address1(line_buffer_0_address1),
    .ce1(line_buffer_0_ce1),
    .q1(line_buffer_0_q1)
);

CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s_line_buffer_0 #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_2_address0),
    .ce0(line_buffer_2_ce0),
    .we0(line_buffer_2_we0),
    .d0(line_buffer_2_d0),
    .q0(line_buffer_2_q0),
    .address1(line_buffer_2_address1),
    .ce1(line_buffer_2_ce1),
    .q1(line_buffer_2_q1)
);

CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s_kernel_conv5 #(
    .DataWidth( 64 ),
    .AddressRange( 576 ),
    .AddressWidth( 10 ))
kernel_conv5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kernel_conv5_address0),
    .ce0(kernel_conv5_ce0),
    .q0(kernel_conv5_q0),
    .address1(kernel_conv5_address1),
    .ce1(kernel_conv5_ce1),
    .q1(kernel_conv5_q1),
    .address2(kernel_conv5_address2),
    .ce2(kernel_conv5_ce2),
    .q2(kernel_conv5_q2),
    .address3(kernel_conv5_address3),
    .ce3(kernel_conv5_ce3),
    .q3(kernel_conv5_q3),
    .address4(kernel_conv5_address4),
    .ce4(kernel_conv5_ce4),
    .q4(kernel_conv5_q4),
    .address5(kernel_conv5_address5),
    .ce5(kernel_conv5_ce5),
    .q5(kernel_conv5_q5),
    .address6(kernel_conv5_address6),
    .ce6(kernel_conv5_ce6),
    .q6(kernel_conv5_q6),
    .address7(kernel_conv5_address7),
    .ce7(kernel_conv5_ce7),
    .q7(kernel_conv5_q7),
    .address8(kernel_conv5_address8),
    .ce8(kernel_conv5_ce8),
    .q8(kernel_conv5_q8)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U212(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_1424),
    .din1(64'd0),
    .ce(1'b1),
    .dout(grp_fu_515_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U213(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_reg_1439),
    .din1(mul_0_1_reg_1429_pp1_iter8_reg),
    .ce(1'b1),
    .dout(grp_fu_520_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U214(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_0_1_reg_1449),
    .din1(mul_0_2_reg_1434_pp1_iter12_reg),
    .ce(1'b1),
    .dout(grp_fu_524_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U215(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_0_2_reg_1460),
    .din1(mul_1_reg_1465),
    .ce(1'b1),
    .dout(grp_fu_528_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U216(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_1_reg_1480),
    .din1(mul_1_1_reg_1470_pp1_iter20_reg),
    .ce(1'b1),
    .dout(grp_fu_532_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U217(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_1_1_reg_1490),
    .din1(mul_1_2_reg_1475_pp1_iter24_reg),
    .ce(1'b1),
    .dout(grp_fu_536_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U218(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_1_2_reg_1501),
    .din1(mul_2_reg_1506),
    .ce(1'b1),
    .dout(grp_fu_540_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U219(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_2_reg_1521),
    .din1(mul_2_1_reg_1511_pp1_iter32_reg),
    .ce(1'b1),
    .dout(grp_fu_544_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U220(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_2_1_reg_1526),
    .din1(mul_2_2_reg_1516_pp1_iter36_reg),
    .ce(1'b1),
    .dout(grp_fu_548_p2)
);

CNN_CNN_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dadd_64ns_64ns_64_4_full_dsp_1_U221(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_1_2_2_reg_1531),
    .din1(select_ln40_1_reg_1284),
    .ce(1'b1),
    .dout(grp_fu_552_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U222(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_0_phi_fu_465_p4),
    .din1(kernel_conv5_load_reg_1289),
    .ce(1'b1),
    .dout(grp_fu_556_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U223(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_1_0_reg_452),
    .din1(kernel_conv5_load_1_reg_1294),
    .ce(1'b1),
    .dout(grp_fu_561_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U224(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_0_load_2_reg_1418_pp1_iter2_reg),
    .din1(kernel_conv5_load_2_reg_1299),
    .ce(1'b1),
    .dout(grp_fu_566_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U225(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_15_phi_fu_486_p4),
    .din1(kernel_conv5_load_3_reg_1304),
    .ce(1'b1),
    .dout(grp_fu_570_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U226(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_1_1_reg_473),
    .din1(kernel_conv5_load_4_reg_1309),
    .ce(1'b1),
    .dout(grp_fu_575_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U227(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_1_load_3_reg_1454_pp1_iter14_reg),
    .din1(kernel_conv5_load_5_reg_1314),
    .ce(1'b1),
    .dout(grp_fu_580_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U228(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_window_buffer_load_26_phi_fu_507_p4),
    .din1(kernel_conv5_load_6_reg_1319),
    .ce(1'b1),
    .dout(grp_fu_584_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U229(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_buffer_load_1_2_reg_494),
    .din1(kernel_conv5_load_7_reg_1324),
    .ce(1'b1),
    .dout(grp_fu_589_p2)
);

CNN_CNN_dmul_64ns_64ns_64_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
CNN_dmul_64ns_64ns_64_4_max_dsp_1_U230(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_2_load_3_reg_1495_pp1_iter26_reg),
    .din1(kernel_conv5_load_8_reg_1329),
    .ce(1'b1),
    .dout(grp_fu_594_p2)
);

CNN_CNN_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
CNN_dcmp_64ns_64ns_1_2_no_dsp_1_U231(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_1536),
    .din1(64'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_598_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U232(
    .din0(shl_ln_fu_603_p3),
    .din1(32'd8),
    .dout(add_ln31_fu_611_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U233(
    .din0(shl_ln_fu_603_p3),
    .din1(32'd7),
    .dout(sub13_fu_623_p2)
);

CNN_CNN_add_32ns_32ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CNN_add_32ns_32ns_32_1_1_U234(
    .din0(shl_ln_fu_603_p3),
    .din1(32'd6),
    .dout(sub47_fu_629_p2)
);

CNN_CNN_add_6ns_6ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
CNN_add_6ns_6ns_6_1_1_U235(
    .din0(add_ln83_1_fu_670_p0),
    .din1(add_ln83_1_fu_670_p1),
    .dout(add_ln83_1_fu_670_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U236(
    .din0(add_ln83_fu_692_p0),
    .din1(add_ln83_fu_692_p1),
    .dout(add_ln83_fu_692_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U237(
    .din0(10'd1),
    .din1(indvar_flatten109_reg_384),
    .dout(add_ln39_fu_704_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U238(
    .din0(4'd1),
    .din1(num_channel_reg_395),
    .dout(add_ln39_1_fu_724_p2)
);

CNN_CNN_add_6ns_6ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
CNN_add_6ns_6ns_6_1_1_U239(
    .din0(add_ln83_2_fu_746_p0),
    .din1(add_ln83_2_fu_746_p1),
    .dout(add_ln83_2_fu_746_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U240(
    .din0(4'd1),
    .din1(select_ln39_fu_716_p3),
    .dout(add_ln40_fu_802_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U241(
    .din0(add_ln83_3_fu_831_p0),
    .din1(add_ln83_3_fu_831_p1),
    .dout(add_ln83_3_fu_831_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U242(
    .din0(10'd1),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_1_fu_850_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U243(
    .din0(10'd2),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_2_fu_861_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U244(
    .din0(10'd3),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_3_fu_872_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U245(
    .din0(10'd4),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_4_fu_883_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U246(
    .din0(10'd5),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_5_fu_894_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U247(
    .din0(10'd6),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_6_fu_905_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U248(
    .din0(10'd7),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_7_fu_916_p2)
);

CNN_CNN_add_10ns_10ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
CNN_add_10ns_10ns_10_1_1_U249(
    .din0(10'd8),
    .din1(select_ln40_2_fu_837_p3),
    .dout(add_ln40_8_fu_927_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U250(
    .din0(j_reg_430),
    .din1(4'd1),
    .dout(add_ln42_fu_998_p2)
);

CNN_CNN_add_31ns_31ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
CNN_add_31ns_31ns_31_1_1_U251(
    .din0(b_reg_441),
    .din1(31'd1),
    .dout(add_ln64_fu_1064_p2)
);

CNN_CNN_add_3ns_3ns_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
CNN_add_3ns_3ns_3_1_1_U252(
    .din0(3'd2),
    .din1(empty_19_fu_1074_p1),
    .dout(empty_19_fu_1074_p2)
);

CNN_CNN_add_4ns_4ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
CNN_add_4ns_4ns_4_1_1_U253(
    .din0(select_ln40_reg_1278),
    .din1(4'd1),
    .dout(add_ln41_fu_1135_p2)
);

CNN_CNN_add_8ns_8ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
CNN_add_8ns_8ns_8_1_1_U254(
    .din0(indvar_flatten_reg_406),
    .din1(8'd1),
    .dout(add_ln40_9_fu_1140_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln42_reg_1158 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln42_reg_1158 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter16 <= ap_enable_reg_pp1_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter17 <= ap_enable_reg_pp1_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter18 <= ap_enable_reg_pp1_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter19 <= ap_enable_reg_pp1_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter20 <= ap_enable_reg_pp1_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter21 <= ap_enable_reg_pp1_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter22 <= ap_enable_reg_pp1_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter23 <= ap_enable_reg_pp1_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter24 <= ap_enable_reg_pp1_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter25 <= ap_enable_reg_pp1_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter25_state34)) begin
                ap_enable_reg_pp1_iter26 <= ap_enable_reg_pp1_iter24;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter26 <= ap_enable_reg_pp1_iter25;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter27 <= ap_enable_reg_pp1_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter28 <= ap_enable_reg_pp1_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter29 <= ap_enable_reg_pp1_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter30 <= ap_enable_reg_pp1_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter31 <= ap_enable_reg_pp1_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter32 <= ap_enable_reg_pp1_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter33 <= ap_enable_reg_pp1_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter34 <= ap_enable_reg_pp1_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter35 <= ap_enable_reg_pp1_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter36 <= ap_enable_reg_pp1_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter37 <= ap_enable_reg_pp1_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter38 <= ap_enable_reg_pp1_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter39 <= ap_enable_reg_pp1_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter40 <= ap_enable_reg_pp1_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter41 <= ap_enable_reg_pp1_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter42 <= ap_enable_reg_pp1_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter43 <= ap_enable_reg_pp1_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter44 <= ap_enable_reg_pp1_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter45 <= ap_enable_reg_pp1_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter46 <= ap_enable_reg_pp1_iter45;
        end else if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp1_iter46 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        b_reg_441 <= 31'd0;
    end else if (((icmp_ln64_fu_1059_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        b_reg_441 <= add_ln64_fu_1064_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        i_reg_418 <= add_ln41_fu_1135_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_418 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        indvar_flatten109_reg_384 <= add_ln39_reg_1200;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten109_reg_384 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        indvar_flatten_reg_406 <= select_ln40_4_fu_1146_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_406 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1158 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j_reg_430 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_fu_993_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_430 <= add_ln42_fu_998_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        num_channel_reg_395 <= select_ln39_4_reg_1218;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        num_channel_reg_395 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        num_ker_reg_372 <= select_ln40_3_reg_1273;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        num_ker_reg_372 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_0_reg_462 <= line_buffer_0_q0;
    end else if (((icmp_ln64_reg_1398_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_0_reg_462 <= window_buffer_load_1_0_reg_452;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_15_reg_483 <= line_buffer_1_q0;
    end else if (((icmp_ln64_reg_1398_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_15_reg_483 <= window_buffer_load_1_1_reg_473;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_1_0_reg_452 <= line_buffer_0_q1;
    end else if (((icmp_ln64_reg_1398_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_1_0_reg_452 <= line_buffer_0_load_2_reg_1418;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_1_1_reg_473 <= line_buffer_1_q1;
    end else if (((icmp_ln64_reg_1398_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_1_1_reg_473 <= line_buffer_1_load_3_reg_1454;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_1_2_reg_494 <= line_buffer_2_q1;
    end else if (((icmp_ln64_reg_1398_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_1_2_reg_494 <= line_buffer_2_load_3_reg_1495;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_buffer_load_26_reg_504 <= line_buffer_2_q0;
    end else if (((icmp_ln64_reg_1398_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        window_buffer_load_26_reg_504 <= window_buffer_load_1_2_reg_494;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        add_ln31_reg_1153 <= add_ln31_fu_611_p2;
        bitcast_ln49_reg_1176 <= bitcast_ln49_fu_641_p1;
        cmp4827_reg_1172 <= cmp4827_fu_635_p2;
        icmp_ln42_reg_1158 <= icmp_ln42_fu_617_p2;
        sub13_reg_1162 <= sub13_fu_623_p2;
        sub47_reg_1167 <= sub47_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln39_reg_1200 <= add_ln39_fu_704_p2;
        bias_conv5_load_reg_1192 <= bias_conv5_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_698_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        and_ln39_reg_1212 <= and_ln39_fu_788_p2;
        icmp_ln40_reg_1205 <= icmp_ln40_fu_710_p2;
        select_ln39_4_reg_1218 <= select_ln39_4_fu_794_p3;
        select_ln40_3_reg_1273 <= select_ln40_3_fu_938_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_15_reg_1181 <= empty_15_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_1_reg_1339 <= icmp_ln42_1_fu_993_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln64_reg_1398 <= icmp_ln64_fu_1059_p2;
        icmp_ln64_reg_1398_pp1_iter1_reg <= icmp_ln64_reg_1398;
        p_cast_reg_1407_pp1_iter1_reg[2 : 0] <= p_cast_reg_1407[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln64_reg_1398_pp1_iter10_reg <= icmp_ln64_reg_1398_pp1_iter9_reg;
        icmp_ln64_reg_1398_pp1_iter11_reg <= icmp_ln64_reg_1398_pp1_iter10_reg;
        icmp_ln64_reg_1398_pp1_iter12_reg <= icmp_ln64_reg_1398_pp1_iter11_reg;
        icmp_ln64_reg_1398_pp1_iter13_reg <= icmp_ln64_reg_1398_pp1_iter12_reg;
        icmp_ln64_reg_1398_pp1_iter14_reg <= icmp_ln64_reg_1398_pp1_iter13_reg;
        icmp_ln64_reg_1398_pp1_iter15_reg <= icmp_ln64_reg_1398_pp1_iter14_reg;
        icmp_ln64_reg_1398_pp1_iter16_reg <= icmp_ln64_reg_1398_pp1_iter15_reg;
        icmp_ln64_reg_1398_pp1_iter17_reg <= icmp_ln64_reg_1398_pp1_iter16_reg;
        icmp_ln64_reg_1398_pp1_iter18_reg <= icmp_ln64_reg_1398_pp1_iter17_reg;
        icmp_ln64_reg_1398_pp1_iter19_reg <= icmp_ln64_reg_1398_pp1_iter18_reg;
        icmp_ln64_reg_1398_pp1_iter20_reg <= icmp_ln64_reg_1398_pp1_iter19_reg;
        icmp_ln64_reg_1398_pp1_iter21_reg <= icmp_ln64_reg_1398_pp1_iter20_reg;
        icmp_ln64_reg_1398_pp1_iter22_reg <= icmp_ln64_reg_1398_pp1_iter21_reg;
        icmp_ln64_reg_1398_pp1_iter23_reg <= icmp_ln64_reg_1398_pp1_iter22_reg;
        icmp_ln64_reg_1398_pp1_iter24_reg <= icmp_ln64_reg_1398_pp1_iter23_reg;
        icmp_ln64_reg_1398_pp1_iter25_reg <= icmp_ln64_reg_1398_pp1_iter24_reg;
        icmp_ln64_reg_1398_pp1_iter26_reg <= icmp_ln64_reg_1398_pp1_iter25_reg;
        icmp_ln64_reg_1398_pp1_iter27_reg <= icmp_ln64_reg_1398_pp1_iter26_reg;
        icmp_ln64_reg_1398_pp1_iter28_reg <= icmp_ln64_reg_1398_pp1_iter27_reg;
        icmp_ln64_reg_1398_pp1_iter29_reg <= icmp_ln64_reg_1398_pp1_iter28_reg;
        icmp_ln64_reg_1398_pp1_iter2_reg <= icmp_ln64_reg_1398_pp1_iter1_reg;
        icmp_ln64_reg_1398_pp1_iter30_reg <= icmp_ln64_reg_1398_pp1_iter29_reg;
        icmp_ln64_reg_1398_pp1_iter31_reg <= icmp_ln64_reg_1398_pp1_iter30_reg;
        icmp_ln64_reg_1398_pp1_iter32_reg <= icmp_ln64_reg_1398_pp1_iter31_reg;
        icmp_ln64_reg_1398_pp1_iter33_reg <= icmp_ln64_reg_1398_pp1_iter32_reg;
        icmp_ln64_reg_1398_pp1_iter34_reg <= icmp_ln64_reg_1398_pp1_iter33_reg;
        icmp_ln64_reg_1398_pp1_iter35_reg <= icmp_ln64_reg_1398_pp1_iter34_reg;
        icmp_ln64_reg_1398_pp1_iter36_reg <= icmp_ln64_reg_1398_pp1_iter35_reg;
        icmp_ln64_reg_1398_pp1_iter37_reg <= icmp_ln64_reg_1398_pp1_iter36_reg;
        icmp_ln64_reg_1398_pp1_iter38_reg <= icmp_ln64_reg_1398_pp1_iter37_reg;
        icmp_ln64_reg_1398_pp1_iter39_reg <= icmp_ln64_reg_1398_pp1_iter38_reg;
        icmp_ln64_reg_1398_pp1_iter3_reg <= icmp_ln64_reg_1398_pp1_iter2_reg;
        icmp_ln64_reg_1398_pp1_iter40_reg <= icmp_ln64_reg_1398_pp1_iter39_reg;
        icmp_ln64_reg_1398_pp1_iter41_reg <= icmp_ln64_reg_1398_pp1_iter40_reg;
        icmp_ln64_reg_1398_pp1_iter42_reg <= icmp_ln64_reg_1398_pp1_iter41_reg;
        icmp_ln64_reg_1398_pp1_iter43_reg <= icmp_ln64_reg_1398_pp1_iter42_reg;
        icmp_ln64_reg_1398_pp1_iter44_reg <= icmp_ln64_reg_1398_pp1_iter43_reg;
        icmp_ln64_reg_1398_pp1_iter45_reg <= icmp_ln64_reg_1398_pp1_iter44_reg;
        icmp_ln64_reg_1398_pp1_iter4_reg <= icmp_ln64_reg_1398_pp1_iter3_reg;
        icmp_ln64_reg_1398_pp1_iter5_reg <= icmp_ln64_reg_1398_pp1_iter4_reg;
        icmp_ln64_reg_1398_pp1_iter6_reg <= icmp_ln64_reg_1398_pp1_iter5_reg;
        icmp_ln64_reg_1398_pp1_iter7_reg <= icmp_ln64_reg_1398_pp1_iter6_reg;
        icmp_ln64_reg_1398_pp1_iter8_reg <= icmp_ln64_reg_1398_pp1_iter7_reg;
        icmp_ln64_reg_1398_pp1_iter9_reg <= icmp_ln64_reg_1398_pp1_iter8_reg;
        line_buffer_0_load_2_reg_1418_pp1_iter2_reg <= line_buffer_0_load_2_reg_1418;
        line_buffer_1_load_3_reg_1454_pp1_iter14_reg <= line_buffer_1_load_3_reg_1454;
        line_buffer_2_load_3_reg_1495_pp1_iter26_reg <= line_buffer_2_load_3_reg_1495;
        mul_0_1_reg_1429_pp1_iter6_reg <= mul_0_1_reg_1429;
        mul_0_1_reg_1429_pp1_iter7_reg <= mul_0_1_reg_1429_pp1_iter6_reg;
        mul_0_1_reg_1429_pp1_iter8_reg <= mul_0_1_reg_1429_pp1_iter7_reg;
        mul_0_2_reg_1434_pp1_iter10_reg <= mul_0_2_reg_1434_pp1_iter9_reg;
        mul_0_2_reg_1434_pp1_iter11_reg <= mul_0_2_reg_1434_pp1_iter10_reg;
        mul_0_2_reg_1434_pp1_iter12_reg <= mul_0_2_reg_1434_pp1_iter11_reg;
        mul_0_2_reg_1434_pp1_iter7_reg <= mul_0_2_reg_1434;
        mul_0_2_reg_1434_pp1_iter8_reg <= mul_0_2_reg_1434_pp1_iter7_reg;
        mul_0_2_reg_1434_pp1_iter9_reg <= mul_0_2_reg_1434_pp1_iter8_reg;
        mul_1_1_reg_1470_pp1_iter18_reg <= mul_1_1_reg_1470;
        mul_1_1_reg_1470_pp1_iter19_reg <= mul_1_1_reg_1470_pp1_iter18_reg;
        mul_1_1_reg_1470_pp1_iter20_reg <= mul_1_1_reg_1470_pp1_iter19_reg;
        mul_1_2_reg_1475_pp1_iter19_reg <= mul_1_2_reg_1475;
        mul_1_2_reg_1475_pp1_iter20_reg <= mul_1_2_reg_1475_pp1_iter19_reg;
        mul_1_2_reg_1475_pp1_iter21_reg <= mul_1_2_reg_1475_pp1_iter20_reg;
        mul_1_2_reg_1475_pp1_iter22_reg <= mul_1_2_reg_1475_pp1_iter21_reg;
        mul_1_2_reg_1475_pp1_iter23_reg <= mul_1_2_reg_1475_pp1_iter22_reg;
        mul_1_2_reg_1475_pp1_iter24_reg <= mul_1_2_reg_1475_pp1_iter23_reg;
        mul_2_1_reg_1511_pp1_iter30_reg <= mul_2_1_reg_1511;
        mul_2_1_reg_1511_pp1_iter31_reg <= mul_2_1_reg_1511_pp1_iter30_reg;
        mul_2_1_reg_1511_pp1_iter32_reg <= mul_2_1_reg_1511_pp1_iter31_reg;
        mul_2_2_reg_1516_pp1_iter31_reg <= mul_2_2_reg_1516;
        mul_2_2_reg_1516_pp1_iter32_reg <= mul_2_2_reg_1516_pp1_iter31_reg;
        mul_2_2_reg_1516_pp1_iter33_reg <= mul_2_2_reg_1516_pp1_iter32_reg;
        mul_2_2_reg_1516_pp1_iter34_reg <= mul_2_2_reg_1516_pp1_iter33_reg;
        mul_2_2_reg_1516_pp1_iter35_reg <= mul_2_2_reg_1516_pp1_iter34_reg;
        mul_2_2_reg_1516_pp1_iter36_reg <= mul_2_2_reg_1516_pp1_iter35_reg;
        p_cast_reg_1407_pp1_iter10_reg[2 : 0] <= p_cast_reg_1407_pp1_iter9_reg[2 : 0];
        p_cast_reg_1407_pp1_iter11_reg[2 : 0] <= p_cast_reg_1407_pp1_iter10_reg[2 : 0];
        p_cast_reg_1407_pp1_iter12_reg[2 : 0] <= p_cast_reg_1407_pp1_iter11_reg[2 : 0];
        p_cast_reg_1407_pp1_iter13_reg[2 : 0] <= p_cast_reg_1407_pp1_iter12_reg[2 : 0];
        p_cast_reg_1407_pp1_iter14_reg[2 : 0] <= p_cast_reg_1407_pp1_iter13_reg[2 : 0];
        p_cast_reg_1407_pp1_iter15_reg[2 : 0] <= p_cast_reg_1407_pp1_iter14_reg[2 : 0];
        p_cast_reg_1407_pp1_iter16_reg[2 : 0] <= p_cast_reg_1407_pp1_iter15_reg[2 : 0];
        p_cast_reg_1407_pp1_iter17_reg[2 : 0] <= p_cast_reg_1407_pp1_iter16_reg[2 : 0];
        p_cast_reg_1407_pp1_iter18_reg[2 : 0] <= p_cast_reg_1407_pp1_iter17_reg[2 : 0];
        p_cast_reg_1407_pp1_iter19_reg[2 : 0] <= p_cast_reg_1407_pp1_iter18_reg[2 : 0];
        p_cast_reg_1407_pp1_iter20_reg[2 : 0] <= p_cast_reg_1407_pp1_iter19_reg[2 : 0];
        p_cast_reg_1407_pp1_iter21_reg[2 : 0] <= p_cast_reg_1407_pp1_iter20_reg[2 : 0];
        p_cast_reg_1407_pp1_iter22_reg[2 : 0] <= p_cast_reg_1407_pp1_iter21_reg[2 : 0];
        p_cast_reg_1407_pp1_iter23_reg[2 : 0] <= p_cast_reg_1407_pp1_iter22_reg[2 : 0];
        p_cast_reg_1407_pp1_iter2_reg[2 : 0] <= p_cast_reg_1407_pp1_iter1_reg[2 : 0];
        p_cast_reg_1407_pp1_iter3_reg[2 : 0] <= p_cast_reg_1407_pp1_iter2_reg[2 : 0];
        p_cast_reg_1407_pp1_iter4_reg[2 : 0] <= p_cast_reg_1407_pp1_iter3_reg[2 : 0];
        p_cast_reg_1407_pp1_iter5_reg[2 : 0] <= p_cast_reg_1407_pp1_iter4_reg[2 : 0];
        p_cast_reg_1407_pp1_iter6_reg[2 : 0] <= p_cast_reg_1407_pp1_iter5_reg[2 : 0];
        p_cast_reg_1407_pp1_iter7_reg[2 : 0] <= p_cast_reg_1407_pp1_iter6_reg[2 : 0];
        p_cast_reg_1407_pp1_iter8_reg[2 : 0] <= p_cast_reg_1407_pp1_iter7_reg[2 : 0];
        p_cast_reg_1407_pp1_iter9_reg[2 : 0] <= p_cast_reg_1407_pp1_iter8_reg[2 : 0];
        sum_reg_1536_pp1_iter45_reg <= sum_reg_1536;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_fu_993_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_cast4_reg_1348[3 : 0] <= j_cast4_fu_1004_p1[3 : 0];
        line_buffer_1_addr_reg_1353 <= j_cast4_fu_1004_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        kernel_conv5_load_1_reg_1294 <= kernel_conv5_q1;
        kernel_conv5_load_2_reg_1299 <= kernel_conv5_q2;
        kernel_conv5_load_3_reg_1304 <= kernel_conv5_q3;
        kernel_conv5_load_4_reg_1309 <= kernel_conv5_q4;
        kernel_conv5_load_5_reg_1314 <= kernel_conv5_q5;
        kernel_conv5_load_6_reg_1319 <= kernel_conv5_q6;
        kernel_conv5_load_7_reg_1324 <= kernel_conv5_q7;
        kernel_conv5_load_8_reg_1329 <= kernel_conv5_q8;
        kernel_conv5_load_reg_1289 <= kernel_conv5_q0;
        select_ln40_1_reg_1284 <= select_ln40_1_fu_964_p3;
        select_ln40_reg_1278 <= select_ln40_fu_956_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_0_load_2_reg_1418 <= line_buffer_0_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter12_reg == 1'd0) & (ap_enable_reg_pp1_iter13 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_1_load_3_reg_1454 <= line_buffer_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter24_reg == 1'd0) & (ap_enable_reg_pp1_iter25 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        line_buffer_2_load_3_reg_1495 <= line_buffer_2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_0_1_reg_1429 <= grp_fu_561_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter5_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_0_2_reg_1434 <= grp_fu_566_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter16_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_1_reg_1470 <= grp_fu_575_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter17_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_2_reg_1475 <= grp_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter15_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_1_reg_1465 <= grp_fu_570_p2;
        sum_1_0_2_reg_1460 <= grp_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter28_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_1_reg_1511 <= grp_fu_589_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter29_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_2_reg_1516 <= grp_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter27_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_2_reg_1506 <= grp_fu_584_p2;
        sum_1_1_2_reg_1501 <= grp_fu_536_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_reg_1424 <= grp_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1158 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        or_ln45_reg_1334 <= or_ln45_fu_983_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_fu_1059_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_cast_reg_1407[2 : 0] <= p_cast_fu_1080_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter11_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_0_1_reg_1449 <= grp_fu_520_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter23_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_1_1_reg_1490 <= grp_fu_532_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter19_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_1_reg_1480 <= grp_fu_528_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter35_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_2_1_reg_1526 <= grp_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter39_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_2_2_reg_1531 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter31_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_2_reg_1521 <= grp_fu_540_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter7_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_1_reg_1439 <= grp_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln64_reg_1398_pp1_iter43_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_reg_1536 <= grp_fu_552_p2;
    end
end

always @ (*) begin
    if ((icmp_ln42_1_fu_993_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter24 == 1'b0) & (ap_enable_reg_pp1_iter25 == 1'b1))) begin
        ap_condition_pp1_exit_iter25_state34 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter25_state34 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln64_fu_1059_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln39_fu_698_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter46 == 1'b0) & (ap_enable_reg_pp1_iter45 == 1'b0) & (ap_enable_reg_pp1_iter44 == 1'b0) & (ap_enable_reg_pp1_iter43 == 1'b0) & (ap_enable_reg_pp1_iter42 == 1'b0) & (ap_enable_reg_pp1_iter41 == 1'b0) & (ap_enable_reg_pp1_iter40 == 1'b0) & (ap_enable_reg_pp1_iter39 == 1'b0) & (ap_enable_reg_pp1_iter38 == 1'b0) & (ap_enable_reg_pp1_iter37 == 1'b0) & (ap_enable_reg_pp1_iter36 == 1'b0) & (ap_enable_reg_pp1_iter35 == 1'b0) & (ap_enable_reg_pp1_iter34 == 1'b0) & (ap_enable_reg_pp1_iter33 == 1'b0) & (ap_enable_reg_pp1_iter32 == 1'b0) & (ap_enable_reg_pp1_iter31 == 1'b0) & (ap_enable_reg_pp1_iter30 == 1'b0) & (ap_enable_reg_pp1_iter29 == 1'b0) & (ap_enable_reg_pp1_iter28 == 1'b0) & (ap_enable_reg_pp1_iter27 == 1'b0) & (ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (ap_enable_reg_pp1_iter23 == 1'b0) & (ap_enable_reg_pp1_iter22 == 1'b0) & (ap_enable_reg_pp1_iter21 == 1'b0) & (ap_enable_reg_pp1_iter20 == 1'b0) & (ap_enable_reg_pp1_iter19 == 1'b0) & (ap_enable_reg_pp1_iter18 == 1'b0) & (ap_enable_reg_pp1_iter17 == 1'b0) & (ap_enable_reg_pp1_iter16 == 1'b0) & (ap_enable_reg_pp1_iter15 == 1'b0) & (ap_enable_reg_pp1_iter14 == 1'b0) & (ap_enable_reg_pp1_iter12 == 1'b0) & (ap_enable_reg_pp1_iter11 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter25 == 1'b0) & (ap_enable_reg_pp1_iter13 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1398_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_0_phi_fu_465_p4 = window_buffer_load_1_0_reg_452;
    end else begin
        ap_phi_mux_window_buffer_load_0_phi_fu_465_p4 = window_buffer_load_0_reg_462;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1398_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_15_phi_fu_486_p4 = window_buffer_load_1_1_reg_473;
    end else begin
        ap_phi_mux_window_buffer_load_15_phi_fu_486_p4 = window_buffer_load_15_reg_483;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (icmp_ln64_reg_1398_pp1_iter25_reg == 1'd0) & (ap_enable_reg_pp1_iter26 == 1'b1))) begin
        ap_phi_mux_window_buffer_load_26_phi_fu_507_p4 = window_buffer_load_1_2_reg_494;
    end else begin
        ap_phi_mux_window_buffer_load_26_phi_fu_507_p4 = window_buffer_load_26_reg_504;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_698_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_conv5_address0 = zext_ln40_1_fu_808_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        bias_conv5_address0 = zext_ln40_fu_645_p1;
    end else begin
        bias_conv5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        bias_conv5_ce0 = 1'b1;
    end else begin
        bias_conv5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce0 = 1'b1;
    end else begin
        kernel_conv5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce1 = 1'b1;
    end else begin
        kernel_conv5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce2 = 1'b1;
    end else begin
        kernel_conv5_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce3 = 1'b1;
    end else begin
        kernel_conv5_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce4 = 1'b1;
    end else begin
        kernel_conv5_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce5 = 1'b1;
    end else begin
        kernel_conv5_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce6 = 1'b1;
    end else begin
        kernel_conv5_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce7 = 1'b1;
    end else begin
        kernel_conv5_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_conv5_ce8 = 1'b1;
    end else begin
        kernel_conv5_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_0_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_address0 = j_cast4_reg_1348;
    end else begin
        line_buffer_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        line_buffer_0_address1 = p_cast_fu_1080_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_0_address1 = 3'd1;
    end else begin
        line_buffer_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_0_ce0 = 1'b1;
    end else begin
        line_buffer_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_0_ce1 = 1'b1;
    end else begin
        line_buffer_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_reg_1339 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_0_we0 = 1'b1;
    end else begin
        line_buffer_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter12 == 1'b1))) begin
        line_buffer_1_address0 = p_cast_reg_1407_pp1_iter11_reg;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_1_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_address0 = j_cast4_fu_1004_p1;
    end else begin
        line_buffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_1_address1 = 3'd1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_address1 = line_buffer_1_addr_reg_1353;
    end else begin
        line_buffer_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp1_iter12 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_1_ce0 = 1'b1;
    end else begin
        line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_1_ce1 = 1'b1;
    end else begin
        line_buffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_reg_1339 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_we1 = 1'b1;
    end else begin
        line_buffer_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_2_address0 = 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln42_1_fu_993_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_2_address0 = j_cast4_fu_1004_p1;
    end else begin
        line_buffer_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter24 == 1'b1))) begin
        line_buffer_2_address1 = p_cast_reg_1407_pp1_iter23_reg;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        line_buffer_2_address1 = 3'd1;
    end else begin
        line_buffer_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_fu_993_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_2_ce0 = 1'b1;
    end else begin
        line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter24 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        line_buffer_2_ce1 = 1'b1;
    end else begin
        line_buffer_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_1_fu_993_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_2_we0 = 1'b1;
    end else begin
        line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln64_reg_1398_pp1_iter45_reg == 1'd0) & (ap_enable_reg_pp1_iter46 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_conv5_ap_vld = 1'b1;
    end else begin
        output_conv5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln39_fu_698_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln42_reg_1158 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln42_1_fu_993_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln42_1_fu_993_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln52_fu_1049_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((cmp4827_reg_1172 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter25 == 1'b1)) & ~((ap_enable_reg_pp1_iter45 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter46 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter45 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter46 == 1'b1)) | ((ap_enable_reg_pp1_iter26 == 1'b0) & (ap_enable_reg_pp1_iter24 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter25 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln83_1_fu_670_p0 = num_channel_reg_395;

assign add_ln83_1_fu_670_p1 = {{empty_fu_658_p1}, {3'd0}};

assign add_ln83_2_fu_746_p0 = add_ln39_1_fu_724_p2;

assign add_ln83_2_fu_746_p1 = {{empty_21_fu_734_p1}, {3'd0}};

assign add_ln83_3_fu_831_p0 = select_ln39_1_fu_756_p3;

assign add_ln83_3_fu_831_p1 = tmp_mid1_fu_817_p4;

assign add_ln83_fu_692_p0 = add_ln83_1_fu_670_p2;

assign add_ln83_fu_692_p1 = tmp_fu_680_p4;

assign and_ln11_fu_1120_p2 = (or_ln11_fu_1114_p2 & grp_fu_598_p2);

assign and_ln39_fu_788_p2 = (xor_ln39_fu_776_p2 & icmp_ln41_fu_782_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp1_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp1_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp1_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp1_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp1_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp1_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp1_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp1_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp1_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp1_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp1_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp1_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp1_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp1_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp1_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp1_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp1_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp1_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp1_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp1_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp1_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp1_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp1_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp1_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp1_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp1_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign b_cast_fu_1055_p1 = b_reg_441;

assign bitcast_ln11_fu_1085_p1 = sum_reg_1536_pp1_iter45_reg;

assign bitcast_ln49_fu_641_p1 = p_read;

assign cmp4827_fu_635_p2 = (($signed(sub47_fu_629_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_15_fu_650_p1 = num_ker_reg_372[2:0];

assign empty_19_fu_1074_p1 = b_reg_441[2:0];

assign empty_21_fu_734_p1 = add_ln39_1_fu_724_p2[2:0];

assign empty_22_fu_813_p1 = add_ln40_fu_802_p2[2:0];

assign empty_fu_658_p1 = num_channel_reg_395[2:0];

assign icmp_ln11_1_fu_1108_p2 = ((trunc_ln11_fu_1098_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_1102_p2 = ((tmp_2_fu_1088_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_698_p2 = ((indvar_flatten109_reg_384 == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_710_p2 = ((indvar_flatten_reg_406 == 8'd80) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_782_p2 = ((i_reg_418 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln42_1_fu_993_p2 = ((j_cast_fu_989_p1 == add_ln31_reg_1153) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_617_p2 = (($signed(add_ln31_fu_611_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_1016_p2 = ((j_cast_fu_989_p1 == sub13_reg_1162) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_971_p2 = ((select_ln40_fu_956_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_977_p2 = ((select_ln40_fu_956_p3 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1010_p2 = ((j_reg_430 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1049_p2 = ((tmp_1_fu_1040_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_1059_p2 = ((b_cast_fu_1055_p1 == sub47_reg_1167) ? 1'b1 : 1'b0);

assign j_cast4_fu_1004_p1 = j_reg_430;

assign j_cast_fu_989_p1 = j_reg_430;

assign kernel_conv5_address0 = zext_ln83_4_fu_845_p1;

assign kernel_conv5_address1 = zext_ln40_2_fu_856_p1;

assign kernel_conv5_address2 = zext_ln40_3_fu_867_p1;

assign kernel_conv5_address3 = zext_ln40_4_fu_878_p1;

assign kernel_conv5_address4 = zext_ln40_5_fu_889_p1;

assign kernel_conv5_address5 = zext_ln40_6_fu_900_p1;

assign kernel_conv5_address6 = zext_ln40_7_fu_911_p1;

assign kernel_conv5_address7 = zext_ln40_8_fu_922_p1;

assign kernel_conv5_address8 = zext_ln40_9_fu_933_p1;

assign line_buffer_2_d0 = ((or_ln45_2_fu_1027_p2[0:0] === 1'b1) ? 64'd0 : bitcast_ln49_reg_1176);

assign or_ln11_fu_1114_p2 = (icmp_ln11_fu_1102_p2 | icmp_ln11_1_fu_1108_p2);

assign or_ln40_fu_952_p2 = (icmp_ln40_reg_1205 | and_ln39_reg_1212);

assign or_ln45_1_fu_1021_p2 = (icmp_ln45_fu_1010_p2 | icmp_ln45_1_fu_1016_p2);

assign or_ln45_2_fu_1027_p2 = (or_ln45_reg_1334 | or_ln45_1_fu_1021_p2);

assign or_ln45_fu_983_p2 = (icmp_ln45_3_fu_977_p2 | icmp_ln45_2_fu_971_p2);

assign output_conv5 = ((and_ln11_fu_1120_p2[0:0] === 1'b1) ? bitcast_ln11_fu_1085_p1 : 64'd0);

assign p_cast_fu_1080_p1 = empty_19_fu_1074_p2;

assign select_ln39_1_fu_756_p3 = ((icmp_ln40_fu_710_p2[0:0] === 1'b1) ? add_ln83_2_fu_746_p2 : add_ln83_1_fu_670_p2);

assign select_ln39_2_fu_946_p3 = ((icmp_ln40_reg_1205[0:0] === 1'b1) ? 64'd4588334987233675288 : bias_conv5_load_reg_1192);

assign select_ln39_3_fu_768_p3 = ((icmp_ln40_fu_710_p2[0:0] === 1'b1) ? zext_ln83_2_fu_752_p1 : add_ln83_fu_692_p2);

assign select_ln39_4_fu_794_p3 = ((icmp_ln40_fu_710_p2[0:0] === 1'b1) ? add_ln39_1_fu_724_p2 : num_channel_reg_395);

assign select_ln39_fu_716_p3 = ((icmp_ln40_fu_710_p2[0:0] === 1'b1) ? 4'd0 : num_ker_reg_372);

assign select_ln40_1_fu_964_p3 = ((and_ln39_reg_1212[0:0] === 1'b1) ? bias_conv5_q0 : select_ln39_2_fu_946_p3);

assign select_ln40_2_fu_837_p3 = ((and_ln39_fu_788_p2[0:0] === 1'b1) ? add_ln83_3_fu_831_p2 : select_ln39_3_fu_768_p3);

assign select_ln40_3_fu_938_p3 = ((and_ln39_fu_788_p2[0:0] === 1'b1) ? add_ln40_fu_802_p2 : select_ln39_fu_716_p3);

assign select_ln40_4_fu_1146_p3 = ((icmp_ln40_reg_1205[0:0] === 1'b1) ? 8'd1 : add_ln40_9_fu_1140_p2);

assign select_ln40_fu_956_p3 = ((or_ln40_fu_952_p2[0:0] === 1'b1) ? 4'd0 : i_reg_418);

assign shl_ln_fu_603_p3 = {{padding}, {1'd0}};

assign tmp_1_fu_1040_p4 = {{select_ln40_reg_1278[3:1]}};

assign tmp_2_fu_1088_p4 = {{bitcast_ln11_fu_1085_p1[62:52]}};

assign tmp_fu_680_p4 = {{{empty_15_reg_1181}, {empty_15_reg_1181}}, {3'd0}};

assign tmp_mid1_fu_817_p4 = {{{empty_22_fu_813_p1}, {empty_22_fu_813_p1}}, {3'd0}};

assign trunc_ln11_fu_1098_p1 = bitcast_ln11_fu_1085_p1[51:0];

assign xor_ln39_fu_776_p2 = (icmp_ln40_fu_710_p2 ^ 1'd1);

assign zext_ln40_1_fu_808_p1 = add_ln40_fu_802_p2;

assign zext_ln40_2_fu_856_p1 = add_ln40_1_fu_850_p2;

assign zext_ln40_3_fu_867_p1 = add_ln40_2_fu_861_p2;

assign zext_ln40_4_fu_878_p1 = add_ln40_3_fu_872_p2;

assign zext_ln40_5_fu_889_p1 = add_ln40_4_fu_883_p2;

assign zext_ln40_6_fu_900_p1 = add_ln40_5_fu_894_p2;

assign zext_ln40_7_fu_911_p1 = add_ln40_6_fu_905_p2;

assign zext_ln40_8_fu_922_p1 = add_ln40_7_fu_916_p2;

assign zext_ln40_9_fu_933_p1 = add_ln40_8_fu_927_p2;

assign zext_ln40_fu_645_p1 = num_ker_reg_372;

assign zext_ln83_2_fu_752_p1 = add_ln83_2_fu_746_p2;

assign zext_ln83_4_fu_845_p1 = select_ln40_2_fu_837_p3;

always @ (posedge ap_clk) begin
    j_cast4_reg_1348[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter5_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter6_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter7_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter8_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter9_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter10_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter11_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter12_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter13_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter14_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter15_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter16_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter17_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter18_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter19_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter20_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter21_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter22_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    p_cast_reg_1407_pp1_iter23_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //CNN_convolution_double_double_double_double_8_8_8_8_8_8_3_3_1_1_s
